#!/bin/bash -e
#
# Dynamically increase the DHCP lease time, requires killing and restarting
# dnsmasq as per documentation (SIGHUP does not reload configuration file).
lease=$1
if [ -z $lease ]; then
    lease="500s"
fi
while [ $(cat /etc/dnsmasq.conf | grep dhcp-range=10.20 | wc -l) == 0 ]; do 
    sleep 1
done
original=$(cat /etc/dnsmasq.conf | grep dhcp-range=10.20 | head -1)
new="$(echo $original | cut -d',' -f 1,2),$lease"
sed -i s/$original/$new/ /etc/dnsmasq.conf

while [ -z $(cat /var/run/dnsmasq.pid) ]; do
    sleep 1
done

kill $(cat /var/run/dnsmasq.pid)
rm /var/run/dnsmasq.pid

dnsmasq --bind-dynamic --log-facility=/tmp/dnsmasq.log --log-dhcp
