#!/bin/bash -e

mkdir -p /tmp/public

(cd /tmp/public; python -m SimpleHTTPServer &)

LOCAL_IF=$HOSTNAME-eth0
EXT_IF=eth0

echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o $EXT_IF -j MASQUERADE
iptables -A FORWARD -i $EXT_IF -o $LOCAL_IF -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $LOCAL_IF -o $EXT_IF -j ACCEPT

dnsmasq -d --bind-dynamic --log-facility=/tmp/dnsmasq.log --log-dhcp
