#!/bin/bash -e

REPORT_FILE=/tmp/report.txt
echo Baseline ping test report > $REPORT_FILE

# This is a check that the startup.pcap file exists and is proper.
echo
ls -l /scans/startup.pcap
echo %% $(tcpdump -n -r /scans/startup.pcap | wc -l) packets captured. | tee -a $REPORT_FILE
echo
tcpdump -en -r /scans/startup.pcap ip
echo
tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: Request"
echo
tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: ACK"
echo

# Setup for accessing control plane switch. If LOCAL_IP is defined, which
# is the intended local address for this node on the control plane then
# SWITCH_IP will be the IP address of the OpenFlow switch.
if [ -n "$LOCAL_IP" ]; then
    echo Configuring network with local address $LOCAL_IP.
    ip addr add $LOCAL_IP dev `hostname`-eth0
    echo Switch test with port $SWITCH_PORT.
    status=pass
    ping -n -c 10 $SWITCH_IP || status=fail
    echo RESULT $status base.switch.ping target $SWITCH_IP:$SWITCH_PORT >> $REPORT_FILE
else
    echo LOCAL_IP not configured, assuming no network switch.
    echo RESULT skip base.switch.ping >> $REPORT_FILE
fi

ping_runtime=/config/port/ping_runtime.sh
if [ -f $ping_runtime ]; then
    echo Executing $ping_runtime
    source $ping_runtime
else
    echo $ping_runtime not found.
fi

# First ping might fail b/c of warm-up delays.
status=pass
ping -n -c 10 $TARGET_IP || status=fail
echo RESULT $status base.target.ping target %% $TARGET_IP >> $REPORT_FILE

echo
echo Done with basic connectivity tests.
