#!/bin/sh -e

LOG=/tmp/nmap.log
OPEN=/tmp/open.txt

nmap --open -oG $LOG $TARGET_HOST

nothing=
grep -oh '[0-9]*/open/[^[:space:]]*' $LOG > $OPEN || nothing=y

echo

if [ -n "$nothing" ]; then
    echo No open ports found.
else
    echo Open ports:
    cat $OPEN
    false
fi
