#!/bin/bash -e
source reporting.sh

RESULT_LINES=/tmp/result_lines.txt
MONO_LOG=/tmp/mono-log.txt
MANIFEST=./module_manifest.json
REPORT_FILE=/tmp/report.txt
status=pass

echo Baseline ping test report | tee -a $MONO_LOG
# This is a check that the startup.pcap file exists and is proper.
tcpdump -en -r /scans/startup.pcap ip

echo %% $(tcpdump -n -r /scans/startup.pcap | wc -l) packets captured. | tee -a $MONO_LOG
echo

STATIC_IP=`jq -r .static_ip /config/device/module_config.json`

if [ -n "$STATIC_IP" ]; then
    echo RESULT skip base.startup.dhcp static ip | tee -a $RESULT_LINES
else
    req=pass
    ack=pass
    echo
    tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: Request" || req=fail
    tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: ACK" || ack=fail1
    if [ $req = "fail" ] || [ $ack = "fail" ]; then
        status=fail
        echo RESULT fail base.startup.dhcp missing dhcp packets| tee -a $RESULT_LINES
    else
        echo RESULT pass base.startup.dhcp | tee -a $RESULT_LINES
    fi
fi

# Setup for accessing control plane switch. If LOCAL_IP is defined, which
# is the intended local address for this node on the control plane then
# SWITCH_IP will be the IP address of the OpenFlow switch.
if [ -n "$LOCAL_IP" ]; then
    echo Configuring network with local address $LOCAL_IP | tee -a $MONO_LOG
    ip addr add $LOCAL_IP dev `hostname`-eth0
    echo Switch test with port $SWITCH_PORT | tee -a $MONO_LOG
    local_status=pass
    ping -n -c 10 $SWITCH_IP || (local_status=fail && status=fail)
    echo RESULT $local_status base.switch.ping target %% $SWITCH_IP:$SWITCH_PORT | tee -a $RESULT_LINES
else
    echo LOCAL_IP not configured, assuming no network switch | tee -a $MONO_LOG
    echo RESULT skip base.switch.ping No local IP has been set, check ext_loip in system.conf | tee -a $RESULT_LINES
fi

ping_runtime=/config/port/ping_runtime.sh
if [ -f $ping_runtime ]; then
    echo Executing $ping_runtime
    source $ping_runtime
else
    echo $ping_runtime not found.
fi

# First ping might fail b/c of warm-up delays.
summary=""
local_status=pass
ping -n -c 10 $TARGET_IP || (local_status=fail && status=fail)

if [ $local_status == pass ]; then
    summary="target reached"
else
    summary="could not reach target"
fi

echo RESULT $local_status base.target.ping $summary %% $TARGET_IP | tee -a $RESULT_LINES

echo | tee -a $MONO_LOG
echo Done with basic connectivity tests | tee -a $MONO_LOG

write_out_monolog $REPORT_FILE \
                  $MANIFEST \
                  $MONO_LOG \
                  $RESULT_LINES

[ "$status" == pass ]
