#!/bin/sh -e

LOG=/tmp/nmap.log
OPEN=/tmp/report.txt

nmap --open -oG $LOG $TARGET_IP

nothing=
grep -oh '[0-9]*/open/[^[:space:]]*' $LOG > $OPEN || nothing=y

echo

if [ -n "$nothing" ]; then
    echo No open ports found.
    echo No open ports found. > $OPEN
else
    echo Open ports:
    cat $OPEN
    false
fi
