#!/bin/bash -e

# This is a check that the startup.pcap file exists and is proper.
echo
ls -l /scans/startup.pcap
echo $(tcpdump -n -r /scans/startup.pcap | wc -l) packets captured.
echo
tcpdump -en -r /scans/startup.pcap ip
echo
tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: Request"
echo
tcpdump -ven -r /scans/startup.pcap port 67 | fgrep "length 1: ACK"
echo

# Setup for accessing control plane switch.
if [ -n "$LOCAL_IP" ]; then
    echo Configuring network with local address $LOCAL_IP
    ip addr add $LOCAL_IP dev `hostname`-eth0
    ping -n -c 5 $SWITCH_IP
fi

# First ping might fail b/c of warm-up delays.
ping -n -c 5 $TARGET_IP

echo
echo Passed basic connectivity tests.
