FROM daq/aardvark:latest 

RUN $AG update && $AG install openjdk-8-jre

RUN $AG update && $AG install openjdk-8-jdk git

RUN $AG update && $AG install curl

COPY subset/connection/ .

RUN curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee mac_oui/src/main/resources/macList.txt

RUN cd mac_oui && ./gradlew shadowJar 

CMD ["./test_macoui"]
