FROM daqf/aardvark:latest

RUN $AG update && $AG install python python-setuptools python-pip netcat

RUN pip install scapy

COPY subset/network/network_tests.py .
COPY subset/network/test_network .

CMD ["./test_network"]
