#!/bin/bash -e 
source reporting.sh

TARGET_MAC=$1
REPORT=$2

LOCAL_REPORT=/report/macoui.txt
CONFIG=/config/device/module_config.json
LOG=/tmp/nmap.log
RESULT_LINES=/tmp/result_lines.txt

TEST_NAME="connection.network.mac_oui"
TEST_DESCRIPTION="Check Physical device address OUI against IEEE registration and verify it is registered with the correct manufacturer"
REDACTED_LOG=/tmp/macoui.report.log

echo Using the host hardware address $TARGET_MAC | tee -a $REDACTED_LOG

java -jar mac_oui/build/libs/mac_oui-all.jar $TARGET_MAC

RESULT_AND_SUMMARY="$(grep "RESULT" $LOCAL_REPORT)"
grep -v "RESULT" $LOCAL_REPORT >> $REDACTED_LOG


TEST_RESULT=$(cat $REDACTED_LOG)

write_out_result $REPORT \
                 "$TEST_NAME" \
                 "$TEST_DESCRIPTION" \
                 "$TEST_RESULT" \
                 "$RESULT_AND_SUMMARY"

# Write result for connection.network.mac_address 
TEST_NAME="connection.network.mac_address"
TEST_DESCRIPTION="Reports device MAC address"
TEST_RESULT="Device MAC address is ${TARGET_MAC}"
RESULT_AND_SUMMARY="RESULT info ${TEST_NAME} ${TEST_RESULT}"

write_out_result $REPORT \
                 "$TEST_NAME" \
                 "$TEST_DESCRIPTION" \
                 "$TEST_RESULT" \
                 "$RESULT_AND_SUMMARY"
