#!/bin/bash -e

REPORT=/tmp/report.txt

STARTUP=/scans/startup.pcap
MONITOR=/scans/monitor.pcap

# General Network Tests
python network_tests.py connection.min_send $MONITOR $TARGET_IP
python network_tests.py communication.type.broadcast $MONITOR $TARGET_IP

cat network_tests.txt >> $REPORT

# NTP Tests
python ntp_tests.py connection.network.ntp_support $STARTUP $MONITOR
python ntp_tests.py connection.network.ntp_update $STARTUP $MONITOR

cat ntp_tests.txt >> $REPORT

# MACOUI Test
./run_macoui_test $TARGET_MAC $REPORT

