#!/bin/bash -e

REPORT=/tmp/report.txt

MONITOR=/scans/monitor.pcap

# General Network Tests
python network_tests.py communication.network.min_send $MONITOR $TARGET_IP
python network_tests.py communication.network.type $MONITOR $TARGET_IP

cat network_tests.txt >> $REPORT

# NTP Tests
python ntp_tests.py ntp.network.ntp_support $MONITOR
python ntp_tests.py ntp.network.ntp_update $MONITOR

cat ntp_tests.txt >> $REPORT

# MACOUI Test
./run_macoui_test $TARGET_MAC $REPORT

# DNS Tests
python dns_tests.py dns.network.hostname_resolution $MONITOR $TARGET_IP

cat dns_tests.txt >> $REPORT
