# DAQ FOT configuration.

include: ${DAQ_LIB}/config/system/default.yaml

base_conf: ${DAQ_LIB}/resources/setups/coupler/base_config.json

host_tests: ${DAQ_LIB}/config/modules/dts.conf

switch_setup:
  lo_port: 6653
  varz_port: 5678

run_trigger:
  vlan_start: 209
  vlan_end: 211

device_reporting:
  server_port: 50051
