#!/bin/bash -e

tunnel_ip=$(ip addr show eth0 | fgrep inet | sed -nr 's~.*inet ([0-9.]+)/.*~\1~p')
grpc_port=50051
target=$(echo $tunnel_ip | sed 's:[^.]*$:1:'):$grpc_port
device_mac="9a:02:57:1e:8f:01"
device_vlan=210
ovs_br="dev_br0"

python3 device_coupler/test_run.py --target $target --source $tunnel_ip --device_mac $device_mac --device_vlan $device_vlan --ovs_br $ovs_br
