#!/bin/bash

# A script which runs the password tests on a given protocol.
# Arguments: $TARGET_IP, $PROTOCOL, $PORT

TARGET_IP=$1
PROTOCOL=$2
PORT=$3

RESULT_FOLDER="reports"
RESULT_FILE="${RESULT_FOLDER}/${PROTOCOL}_result.txt"

function run_nmap_and_get_command() {
  NMAP_OUTPUT=$(nmap -p $2 $1)
  echo "$NMAP_OUTPUT"
}

function is_specified_port_open() {
  echo "$1" | grep -q "$3.*open.*$2"
}

function can_connect_to_host() {
  echo "$1" | grep -q "Host seems down"
}

function run_brute_force_and_get_command() {
  if [ "$2" == "http" ]; then
    hydra_output=$(hydra -C resources/dictionary.txt $1 http-get -s $3)
    echo "$hydra_output"
  elif [ "$2" == "https" ]; then
    hydra_output=$(hydra -C resources/dictionary.txt $1 https-get -s $3)
    echo "$hydra_output"
  else
    hydra_output=$(hydra -C resources/dictionary.txt $1 $2 -s $3)
    echo "$hydra_output"
  fi
}

function brute_force_successful() {
  echo "$1" | grep -q "successfully completed"
}

function brute_force_skip() {
  echo "$1" | grep -q "[ERROR]"
}

function brute_force_unsuccessful() {
  echo "$1" | grep -q "0 valid passwords found"
}

function write_to_result_file() {
  mkdir -p $RESULT_FOLDER

  if [ -f $RESULT_FILE ]; then
    rm $RESULT_FILE
  fi
  touch $RESULT_FILE

  if [ "$3" == "pass" ]; then
    echo "RESULT pass security.passwords.$1 Was not able to brute force using dictionary." > $RESULT_FILE
  elif [ "$3" == "fail" ]; then
    echo "RESULT fail security.passwords.$1 Was able to brute force using dictionary." > $RESULT_FILE
  elif [ "$3" == "skip_no_host" ]; then
    echo "RESULT skip security.passwords.$1 Unable to connect to host." > $RESULT_FILE
  elif [ "$3" == "skip_no_port" ]; then
    echo "RESULT skip security.passwords.$1 Port $2 not open on target device." > $RESULT_FILE
  elif [ "$3" == "skip_hydra_error" ]; then
    echo "RESULT skip security.passwords.$1 Skipping due to hydra error, please see log." > $RESULT_FILE
  fi
}

NMAP_OUTPUT="$(run_nmap_and_get_command $TARGET_IP $PORT)"
echo "$NMAP_OUTPUT"

if ! can_connect_to_host "$NMAP_OUTPUT"; then

  if is_specified_port_open "$NMAP_OUTPUT" $PROTOCOL $PORT; then
    BRUTE_FORCE_OUTPUT="$(run_brute_force_and_get_command $TARGET_IP $PROTOCOL $PORT)"
    echo "$BRUTE_FORCE_OUTPUT"

    if brute_force_skip "$BRUTE_FORCE_OUTPUT" $PROTOCOL; then
      echo "Could not brute force due to hydra error."
      RESULT="skip_hydra_error"
    elif brute_force_unsuccessful "$BRUTE_FORCE_OUTPUT" $PROTOCOL; then
      echo "Could not brute force using dictionary."
      RESULT="pass"
    elif brute_force_successful "$BRUTE_FORCE_OUTPUT" $PROTOCOL; then
      echo "Was able to brute force using dictionary."
      RESULT="fail"
    fi

  else
    echo "Could not connect to specified port on host."
    RESULT="skip_no_port"
  fi

else
  echo "Could not connect to host."
  RESULT="skip_no_host"
fi

write_to_result_file $PROTOCOL $PORT $RESULT
