#!/bin/bash -e

# Entry point for the security.admin.password test - Runs the test on all protocols <http|https|telnet|ssh> in parallel
# and writes the output into reports file to be used by DAQ.
# Usage: Run with no arguments, relies on environment variables exported by DAQ e.g. $TARGET_IP/$TARGET_MAC

source reporting.sh

HTTP="HTTP"
HTTPS="HTTPS"
TELNET="Telnet"
SSH="SSH"
REPORT=reports/report.txt

# Makes the log files in the tmp folder. These files hold the output of the run_password_test_for_protocol command.
make_log_files() {
  touch /tmp/http_report.txt
  touch /tmp/https_report.txt
  touch /tmp/telnet_report.txt
  touch /tmp/ssh_report.txt
}

# Sets test description for a given protocol.
# $1 Target protocol
set_test_desc() {
  TEST_DESC="Verify all device manufacturer default passwords are changed for protocol: $1, and new passwords are set."
}

# Runs the password test on all protocols in parallel, writes output to the log files.
# $1 Target IP
run_password_test_all_protocols () {
  ./run_password_test_for_protocol $1 http 80 &> /tmp/http_report.txt &
  ./run_password_test_for_protocol $1 https 443 &> /tmp/https_report.txt &
  ./run_password_test_for_protocol $1 telnet 23 &> /tmp/telnet_report.txt &
  ./run_password_test_for_protocol $1 ssh 22 &> /tmp/ssh_report.txt &
  wait
}

if [ -n "$TARGET_IP" ]; then
  run_password_test_all_protocols $TARGET_IP

  make_log_files

  set_test_desc $HTTP

  write_out_result $REPORT \
    "security.passwords.http" \
    "$TEST_DESC" \
    "$(cat /tmp/http_report.txt)" \
    "$(cat reports/http_result.txt)"

  set_test_desc $HTTPS

  write_out_result $REPORT \
    "security.passwords.https" \
    "$TEST_DESC" \
    "$(cat /tmp/https_report.txt)" \
    "$(cat reports/https_result.txt)"

  set_test_desc $TELNET

  write_out_result $REPORT \
    "security.passwords.telnet" \
    "$TEST_DESC" \
    "$(cat /tmp/telnet_report.txt)" \
    "$(cat reports/telnet_result.txt)"

  set_test_desc $SSH

  write_out_result $REPORT \
    "security.passwords.ssh" \
    "$TEST_DESC" \
    "$(cat /tmp/ssh_report.txt)" \
    "$(cat reports/ssh_result.txt)"

  cp -r $REPORT /tmp/report.txt
else
  echo Problem with target IP, password test cannot continue. | tee /tmp/report.txt
fi
