#!/bin/bash -e

# Entry point for the security.admin.password test - Runs the test on all protocols <http|https|telnet|ssh> in parallel
# and writes the output into reports file to be used by DAQ.

source reporting.sh

# Hard coded paths.
DAQ_REPORT="/tmp/report.txt"
RESULTS_DIR="/tmp/results"
LOG_DIR="/tmp/logs"
MODULE_CONFIG="/tmp/module_config.json"

# Hard coded files and names.
HTTP_LOG="$LOG_DIR/security_password_http.log"
HTTPS_LOG="$LOG_DIR/security_password_https.log"
SSH_LOG="$LOG_DIR/security_password_ssh.log"
TELNET_LOG="$LOG_DIR/security_password_telnet.log"

HTTP_RESULT="$RESULTS_DIR/security_password_http.result"
HTTPS_RESULT="$RESULTS_DIR/security_password_https.result"
SSH_RESULT="$RESULTS_DIR/security_password_ssh.result"
TELNET_RESULT="$RESULTS_DIR/security_password_telnet.result"

# Hard coded json keys for jq
DICTIONARY_DIR_KEY=".modules.password.dictionary_dir"
HTTP_PORT_KEY=".modules.password.http_port"
HTTPS_PORT_KEY=".modules.password.https_port"
SSH_PORT_KEY=".modules.password.ssh_port"
TELNET_PORT_KEY=".modules.password.telnet_port"

# Default configuration values.
DICTIONARY_DIR="resources/default"
HTTP_PORT=80
HTTPS_PORT=443
SSH_PORT=22
TELNET_PORT=23

# Retrieves the value specified in provided key from the module config.
# $1 Module config file path
# $2 jq JSON key string
function get_module_config_value_from_key() {
  cat $1 | jq $2 | tr -d '"'
}

# Retrieve a modified version of the test description for a protocol.
# $1 Protocol name
function get_test_description() {
  echo "Verify all device manufacturer default passwords are changed for protocol: $1, and new passwords are set."
}

# Retrieve a modified version of the test name for a protocol.
# $1 Protocol name
function get_test_name() {
  echo "security.admin.password.$1"
}

# Main function

echo "Password test starting on docker container: $TARGET_IP..."

echo "Checking module_config.json for any default configurations to overwrite..."
NEW_DICTIONARY_DIR="$(get_module_config_value_from_key $MODULE_CONFIG $DICTIONARY_DIR_KEY)"
NEW_HTTP_PORT="$(get_module_config_value_from_key $MODULE_CONFIG $HTTP_PORT_KEY)"
NEW_HTTPS_PORT="$(get_module_config_value_from_key $MODULE_CONFIG $HTTPS_PORT_KEY)"
NEW_SSH_PORT="$(get_module_config_value_from_key $MODULE_CONFIG $SSH_PORT_KEY)"
NEW_TELNET_PORT="$(get_module_config_value_from_key $MODULE_CONFIG $TELNET_PORT_KEY)"

echo "Overwriting default configurations with user specified values... (If any)"
[ $NEW_DICTIONARY_DIR != "null" ] && DICTIONARY_DIR=$NEW_DICTIONARY_DIR
[ $NEW_HTTP_PORT != "null" ] && HTTP_PORT=$NEW_HTTP_PORT
[ $NEW_HTTPS_PORT != "null" ] && HTTPS_PORT=$NEW_HTTPS_PORT
[ $NEW_SSH_PORT != "null" ] && SSH_PORT=$NEW_SSH_PORT
[ $NEW_TELNET_PORT != "null" ] && TELNET_PORT=$NEW_TELNET_PORT

echo "Print out configurations set..."
echo "DICTIONARY_DIR: $DICTIONARY_DIR"
echo "HTTP_PORT: $HTTP_PORT"
echo "HTTPS_PORT: $HTTPS_PORT"
echo "SSH_PORT: $SSH_PORT"
echo "TELNET_PORT: $TELNET_PORT"

echo "Running password test for each protocol..."
mkdir -p $LOG_DIR
./run_password_test_for_protocol $TARGET_IP http $HTTP_PORT $DICTIONARY_DIR $RESULTS_DIR &> $HTTP_LOG &
./run_password_test_for_protocol $TARGET_IP https $HTTPS_PORT $DICTIONARY_DIR $RESULTS_DIR &> $HTTPS_LOG &
./run_password_test_for_protocol $TARGET_IP ssh $SSH_PORT $DICTIONARY_DIR $RESULTS_DIR &> $SSH_LOG &
./run_password_test_for_protocol $TARGET_IP telnet $TELNET_PORT $DICTIONARY_DIR $RESULTS_DIR &> $TELNET_LOG &
wait

echo "Writing test results and logs to DAQ report..."
write_out_result $DAQ_REPORT "$(get_test_name "http")" "$(get_test_description "http")" "$(cat $HTTP_LOG)" "$(cat $HTTP_RESULT)"
write_out_result $DAQ_REPORT "$(get_test_name "https")" "$(get_test_description "https")" "$(cat $HTTPS_LOG)" "$(cat $HTTPS_RESULT)"
write_out_result $DAQ_REPORT "$(get_test_name "ssh")" "$(get_test_description "ssh")" "$(cat $SSH_LOG)" "$(cat $SSH_RESULT)"
write_out_result $DAQ_REPORT "$(get_test_name "telnet")" "$(get_test_description "telnet")" "$(cat $TELNET_LOG)" "$(cat $TELNET_RESULT)"

echo "Done!"
