---
linters:
  flake8:
    python: 3
    max-line-length: 100
    ignore: E1601
  pep8:
    python: 3
    max-line-length: 100
    ignore: E1601
  py3k:
    ignore: E1601
  checkstyle:
    config: ./.checkstyle.xml
files:
  ignore:
    - 'libs/proto/*'
