---
linters:
  flake8:
    python: 3
    max-line-length: 100
  pep8:
    python: 3
    max-line-length: 100
  py3k:
    ignore: E1601
  checkstyle:
    config: ./.checkstyle.xml
files:
  ignore:
    - 'daq/proto/*'
    - '*__init__.py'
