#!/bin/bash -ex
export GIT_URL=git@github.com:grafnu/daq.git
rm -rf forch
bin/setup_remote forch
git rev-list HEAD --max-count=1 > forch/etc/DAQ_VERSION
cd forch
PVERSION=3.9 bin/setup_base
bin/setup_remote faucet
bin/setup_remote daq
bin/retry_cmd bin/build_docker controller
bin/build_dts
