version: '2'

services:
    host_client:
        build:
            context: ../..
            dockerfile: ./testing/shunt/Dockerfile.shunthost
        depends_on:
            - "host_server"
        command: bash -c "./start_shunt_host 1"
        #command: bash -c "tail -f"
        cap_add:
            - ALL
    host_server:
        build:
            context: ../..
            dockerfile: ./testing/shunt/Dockerfile.shunthost
        command: bash -c "./start_shunt_host 2"
        #command: bash -c "tail -f"
        cap_add:
            - ALL
