# Image name: daqf/default
#
# Default image used for mininet docker hosts.
#

FROM daqf/aardvark

RUN $AG update && $AG install openssh-server socat sudo iptables python3-dev

COPY ./testing/shunt/id_rsa .ssh/
COPY ./testing/shunt/id_rsa.pub .ssh/
COPY ./testing/shunt/authorized_keys .ssh/
COPY ./testing/shunt/start_shunt_host ./

RUN mkdir -p python_lib
RUN mkdir -p shunt
RUN mkdir -p testing
RUN mkdir -p testing/shunt

COPY ./python_lib python_lib
COPY ./shunt shunt
COPY ./testing/shunt testing/shunt

RUN chmod -R 700 .ssh

RUN service ssh start

COPY ./bin/shunt_functions bin/
