#!/bin/bash
#

host=$1
service ssh start
source bin/shunt_functions

pwd
ls -a
export PYTHONPATH=$PYTHONPATH:/root/shunt

if [ $host -eq 1 ]; then
    #build_ssh_tunnel 30001 30000 shunt_host_server_1
    #build_vxlan_ssh_conn 30001 30000 192.168.1.1
    python3 testing/shunt/build_vxlan_ssh_conn.py client
else
    #build_vxlan_ssh_conn 30001 30000 192.168.1.2
    python3 testing/shunt/build_vxlan_ssh_conn.py server
fi

tail -f /dev/null
