#!/bin/bash
#

host=$1
service ssh start
source bin/shunt_functions

if [ $host -eq 1 ]; then
    build_ssh_tunnel 30001 30000 shunt_host2_1
    build_vxlan_ssh_conn 30001 30000 1 192.168.1.1
else
    build_vxlan_ssh_conn 30001 30000 1 192.168.1.2
fi

tail -f /dev/null
