#!/bin/bash -e

REPORT=/tmp/report.txt
STARTUP=/scans/startup.pcap
MONITOR=/scans/monitor.pcap

python ntp_tests.py connection.network.ntp_support $STARTUP $MONITOR
python ntp_tests.py connection.network.ntp_update $STARTUP $MONITOR

cat report.txt >> $REPORT
