# Dockerfile for running the password test locally and the corresponding faux device.
# Make sure when building this image, the working directory specified in command is DAQ folder.

FROM daq/aardvark:latest

# Initial dependencies
RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git
RUN $AG update && $AG install python openssl ssh nmap

# Get password test dependencies
RUN $AG update && $AG install curl
RUN $AG update && $AG install ncrack

# Setup source folder in container
COPY subset/security .
RUN curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee security_passwords/src/main/resources/macList.txt
RUN cd security_passwords && ./gradlew shadowJar

# Run the pass test
CMD ["security_passwords/src/main/test/test_docker_files/run_password_tests.sh", "172.17.0.2", "172.17.0.3", "172.17.0.4", "9a:02:57:1e:8f:01"]
