# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/device_coupler.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/device_coupler.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x64\x61q/proto/device_coupler.proto\"h\n\x14\x44\x65viceDiscoveryEvent\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x0c\n\x04vlan\x18\x02 \x01(\x05\x12\x0b\n\x03mac\x18\x03 \x01(\t\x12\'\n\nevent_type\x18\x04 \x01(\x0e\x32\x13.DiscoveryEventType*/\n\x12\x44iscoveryEventType\x12\n\n\x06\x45XPIRY\x10\x00\x12\r\n\tDISCOVERY\x10\x01\x62\x06proto3'
)

_DISCOVERYEVENTTYPE = _descriptor.EnumDescriptor(
  name='DiscoveryEventType',
  full_name='DiscoveryEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXPIRY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISCOVERY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_DISCOVERYEVENTTYPE)

DiscoveryEventType = enum_type_wrapper.EnumTypeWrapper(_DISCOVERYEVENTTYPE)
EXPIRY = 0
DISCOVERY = 1



_DEVICEDISCOVERYEVENT = _descriptor.Descriptor(
  name='DeviceDiscoveryEvent',
  full_name='DeviceDiscoveryEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='DeviceDiscoveryEvent.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vlan', full_name='DeviceDiscoveryEvent.vlan', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mac', full_name='DeviceDiscoveryEvent.mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='DeviceDiscoveryEvent.event_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=138,
)

_DEVICEDISCOVERYEVENT.fields_by_name['event_type'].enum_type = _DISCOVERYEVENTTYPE
DESCRIPTOR.message_types_by_name['DeviceDiscoveryEvent'] = _DEVICEDISCOVERYEVENT
DESCRIPTOR.enum_types_by_name['DiscoveryEventType'] = _DISCOVERYEVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceDiscoveryEvent = _reflection.GeneratedProtocolMessageType('DeviceDiscoveryEvent', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEDISCOVERYEVENT,
  '__module__' : 'daq.proto.device_coupler_pb2'
  # @@protoc_insertion_point(class_scope:DeviceDiscoveryEvent)
  })
_sym_db.RegisterMessage(DeviceDiscoveryEvent)


# @@protoc_insertion_point(module_scope)
