# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from daq.proto import device_testing_pb2 as daq_dot_proto_dot_device__testing__pb2


class DeviceTestingStub(object):
    """
    Device testing service endpoint.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_stream(
                '/DeviceTesting/StartSession',
                request_serializer=daq_dot_proto_dot_device__testing__pb2.SessionParams.SerializeToString,
                response_deserializer=daq_dot_proto_dot_device__testing__pb2.SessionProgress.FromString,
                )


class DeviceTestingServicer(object):
    """
    Device testing service endpoint.
    """

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceTestingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_stream_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=daq_dot_proto_dot_device__testing__pb2.SessionParams.FromString,
                    response_serializer=daq_dot_proto_dot_device__testing__pb2.SessionProgress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeviceTesting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceTesting(object):
    """
    Device testing service endpoint.
    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DeviceTesting/StartSession',
            daq_dot_proto_dot_device__testing__pb2.SessionParams.SerializeToString,
            daq_dot_proto_dot_device__testing__pb2.SessionProgress.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
