# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/report.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/report.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x64\x61q/proto/report.proto\"x\n\x0c\x44\x65viceReport\x12+\n\x07modules\x18\x01 \x03(\x0b\x32\x1a.DeviceReport.ModulesEntry\x1a;\n\x0cModulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.TestModule:\x02\x38\x01\"l\n\nTestModule\x12%\n\x05tests\x18\x01 \x03(\x0b\x32\x16.TestModule.TestsEntry\x1a\x37\n\nTestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.TestItem:\x02\x38\x01\"\x82\x01\n\x08TestItem\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x11\n\ttest_name\x18\x02 \x01(\t\x12\x13\n\x0bmodule_name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x10\n\x08\x65xpected\x18\x05 \x01(\t\x12\x1a\n\x12result_description\x18\x06 \x01(\tb\x06proto3'
)




_DEVICEREPORT_MODULESENTRY = _descriptor.Descriptor(
  name='ModulesEntry',
  full_name='DeviceReport.ModulesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DeviceReport.ModulesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DeviceReport.ModulesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=146,
)

_DEVICEREPORT = _descriptor.Descriptor(
  name='DeviceReport',
  full_name='DeviceReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='DeviceReport.modules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEREPORT_MODULESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=146,
)


_TESTMODULE_TESTSENTRY = _descriptor.Descriptor(
  name='TestsEntry',
  full_name='TestModule.TestsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TestModule.TestsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='TestModule.TestsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=256,
)

_TESTMODULE = _descriptor.Descriptor(
  name='TestModule',
  full_name='TestModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tests', full_name='TestModule.tests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TESTMODULE_TESTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=256,
)


_TESTITEM = _descriptor.Descriptor(
  name='TestItem',
  full_name='TestItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='TestItem.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_name', full_name='TestItem.test_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='module_name', full_name='TestItem.module_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='TestItem.category', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expected', full_name='TestItem.expected', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result_description', full_name='TestItem.result_description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=389,
)

_DEVICEREPORT_MODULESENTRY.fields_by_name['value'].message_type = _TESTMODULE
_DEVICEREPORT_MODULESENTRY.containing_type = _DEVICEREPORT
_DEVICEREPORT.fields_by_name['modules'].message_type = _DEVICEREPORT_MODULESENTRY
_TESTMODULE_TESTSENTRY.fields_by_name['value'].message_type = _TESTITEM
_TESTMODULE_TESTSENTRY.containing_type = _TESTMODULE
_TESTMODULE.fields_by_name['tests'].message_type = _TESTMODULE_TESTSENTRY
DESCRIPTOR.message_types_by_name['DeviceReport'] = _DEVICEREPORT
DESCRIPTOR.message_types_by_name['TestModule'] = _TESTMODULE
DESCRIPTOR.message_types_by_name['TestItem'] = _TESTITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceReport = _reflection.GeneratedProtocolMessageType('DeviceReport', (_message.Message,), {

  'ModulesEntry' : _reflection.GeneratedProtocolMessageType('ModulesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICEREPORT_MODULESENTRY,
    '__module__' : 'daq.proto.report_pb2'
    # @@protoc_insertion_point(class_scope:DeviceReport.ModulesEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICEREPORT,
  '__module__' : 'daq.proto.report_pb2'
  # @@protoc_insertion_point(class_scope:DeviceReport)
  })
_sym_db.RegisterMessage(DeviceReport)
_sym_db.RegisterMessage(DeviceReport.ModulesEntry)

TestModule = _reflection.GeneratedProtocolMessageType('TestModule', (_message.Message,), {

  'TestsEntry' : _reflection.GeneratedProtocolMessageType('TestsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TESTMODULE_TESTSENTRY,
    '__module__' : 'daq.proto.report_pb2'
    # @@protoc_insertion_point(class_scope:TestModule.TestsEntry)
    })
  ,
  'DESCRIPTOR' : _TESTMODULE,
  '__module__' : 'daq.proto.report_pb2'
  # @@protoc_insertion_point(class_scope:TestModule)
  })
_sym_db.RegisterMessage(TestModule)
_sym_db.RegisterMessage(TestModule.TestsEntry)

TestItem = _reflection.GeneratedProtocolMessageType('TestItem', (_message.Message,), {
  'DESCRIPTOR' : _TESTITEM,
  '__module__' : 'daq.proto.report_pb2'
  # @@protoc_insertion_point(class_scope:TestItem)
  })
_sym_db.RegisterMessage(TestItem)


_DEVICEREPORT_MODULESENTRY._options = None
_TESTMODULE_TESTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
