# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/session_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/session_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x64\x61q/proto/session_server.proto\"r\n\rSessionParams\x12\x12\n\ndevice_mac\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_vlan\x18\x02 \x01(\x05\x12\x15\n\rassigned_vlan\x18\x03 \x01(\x05\x12!\n\x08\x65ndpoint\x18\x04 \x01(\x0b\x32\x0f.TunnelEndpoint\"d\n\x0fSessionProgress\x12#\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32\x0f.TunnelEndpointH\x00\x12 \n\x06result\x18\x02 \x01(\x0b\x32\x0e.SessionResultH\x00\x42\n\n\x08progress\"7\n\x0eTunnelEndpoint\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0b\n\x03vni\x18\x03 \x01(\x05\"\x83\x01\n\rSessionResult\x12\'\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x19.SessionResult.ResultCode\"I\n\nResultCode\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\n\n\x06PASSED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x32}\n\rSessionServer\x12\x34\n\x0cStartSession\x12\x0e.SessionParams\x1a\x10.SessionProgress\"\x00\x30\x01\x12\x36\n\x11\x43onfigureEndpoint\x12\x0f.TunnelEndpoint\x1a\x0e.SessionResult\"\x00\x62\x06proto3'
)



_SESSIONRESULT_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='SessionResult.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STARTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PASSED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=368,
  serialized_end=441,
)
_sym_db.RegisterEnumDescriptor(_SESSIONRESULT_RESULTCODE)


_SESSIONPARAMS = _descriptor.Descriptor(
  name='SessionParams',
  full_name='SessionParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_mac', full_name='SessionParams.device_mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_vlan', full_name='SessionParams.device_vlan', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assigned_vlan', full_name='SessionParams.assigned_vlan', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='SessionParams.endpoint', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=148,
)


_SESSIONPROGRESS = _descriptor.Descriptor(
  name='SessionProgress',
  full_name='SessionProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='SessionProgress.endpoint', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='SessionProgress.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='progress', full_name='SessionProgress.progress',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=150,
  serialized_end=250,
)


_TUNNELENDPOINT = _descriptor.Descriptor(
  name='TunnelEndpoint',
  full_name='TunnelEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='TunnelEndpoint.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='TunnelEndpoint.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vni', full_name='TunnelEndpoint.vni', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=307,
)


_SESSIONRESULT = _descriptor.Descriptor(
  name='SessionResult',
  full_name='SessionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='SessionResult.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SESSIONRESULT_RESULTCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=441,
)

_SESSIONPARAMS.fields_by_name['endpoint'].message_type = _TUNNELENDPOINT
_SESSIONPROGRESS.fields_by_name['endpoint'].message_type = _TUNNELENDPOINT
_SESSIONPROGRESS.fields_by_name['result'].message_type = _SESSIONRESULT
_SESSIONPROGRESS.oneofs_by_name['progress'].fields.append(
  _SESSIONPROGRESS.fields_by_name['endpoint'])
_SESSIONPROGRESS.fields_by_name['endpoint'].containing_oneof = _SESSIONPROGRESS.oneofs_by_name['progress']
_SESSIONPROGRESS.oneofs_by_name['progress'].fields.append(
  _SESSIONPROGRESS.fields_by_name['result'])
_SESSIONPROGRESS.fields_by_name['result'].containing_oneof = _SESSIONPROGRESS.oneofs_by_name['progress']
_SESSIONRESULT.fields_by_name['code'].enum_type = _SESSIONRESULT_RESULTCODE
_SESSIONRESULT_RESULTCODE.containing_type = _SESSIONRESULT
DESCRIPTOR.message_types_by_name['SessionParams'] = _SESSIONPARAMS
DESCRIPTOR.message_types_by_name['SessionProgress'] = _SESSIONPROGRESS
DESCRIPTOR.message_types_by_name['TunnelEndpoint'] = _TUNNELENDPOINT
DESCRIPTOR.message_types_by_name['SessionResult'] = _SESSIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SessionParams = _reflection.GeneratedProtocolMessageType('SessionParams', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONPARAMS,
  '__module__' : 'daq.proto.session_server_pb2'
  # @@protoc_insertion_point(class_scope:SessionParams)
  })
_sym_db.RegisterMessage(SessionParams)

SessionProgress = _reflection.GeneratedProtocolMessageType('SessionProgress', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONPROGRESS,
  '__module__' : 'daq.proto.session_server_pb2'
  # @@protoc_insertion_point(class_scope:SessionProgress)
  })
_sym_db.RegisterMessage(SessionProgress)

TunnelEndpoint = _reflection.GeneratedProtocolMessageType('TunnelEndpoint', (_message.Message,), {
  'DESCRIPTOR' : _TUNNELENDPOINT,
  '__module__' : 'daq.proto.session_server_pb2'
  # @@protoc_insertion_point(class_scope:TunnelEndpoint)
  })
_sym_db.RegisterMessage(TunnelEndpoint)

SessionResult = _reflection.GeneratedProtocolMessageType('SessionResult', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONRESULT,
  '__module__' : 'daq.proto.session_server_pb2'
  # @@protoc_insertion_point(class_scope:SessionResult)
  })
_sym_db.RegisterMessage(SessionResult)



_SESSIONSERVER = _descriptor.ServiceDescriptor(
  name='SessionServer',
  full_name='SessionServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=443,
  serialized_end=568,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartSession',
    full_name='SessionServer.StartSession',
    index=0,
    containing_service=None,
    input_type=_SESSIONPARAMS,
    output_type=_SESSIONPROGRESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigureEndpoint',
    full_name='SessionServer.ConfigureEndpoint',
    index=1,
    containing_service=None,
    input_type=_TUNNELENDPOINT,
    output_type=_SESSIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONSERVER)

DESCRIPTOR.services_by_name['SessionServer'] = _SESSIONSERVER

# @@protoc_insertion_point(module_scope)
