apiVersion: apps/v1
kind: Deployment
metadata:
  name: dts
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: "us.gcr.io/dts-scale-testing/dts:c7a17ce3d00a"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 101Mi
            cpu: 120m
        securityContext:
          privileged: true
        volumeMounts:
        - name: daq-config
          mountPath: /daq-config
      volumes:
      - name: daq-config
        configMap:
          name: daq-configmap

