apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dts
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 95
