apiVersion: v1
kind: Service
metadata:
  name: ilb-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: ilb-internal
spec:
  type: LoadBalancer
  selector:
    app: hello 
  ports:
  - port: 50051
    protocol: TCP
