#!/usr/bin/env python3
"""Simple utility to relay ARP packets in on one interface, then out another."""

import sys
from scapy.all import sendp, sniff, ARP

IFACE_IN = sys.argv[1]
IFACE_OUT = sys.argv[2]

print('Relay ARP from %s to %s' % (IFACE_IN, IFACE_OUT))

def arp_monitor_callback(pkt):
    """Receive an ARP packet and forward it out the other interface"""
    if ARP in pkt:
        print('Relay ARP %s' % pkt.sprintf("%ARP.hwsrc% %ARP.psrc%"))
        sendp(pkt, iface=IFACE_OUT, verbose=False)

sniff(iface=IFACE_IN, prn=arp_monitor_callback, filter="arp", store=0)
