FROM daq/aardvark:latest

RUN $AG install default-jdk git

RUN git clone https://github.com/grafnu/bacnet4j.git

RUN cd bacnet4j && ./gradlew --help

RUN cd bacnet4j && ./gradlew

RUN cd bacnet4j && ./gradlew shadow

COPY misc/bacnet_discover .

CMD ["./bacnet_discover"]
