FROM daq/aardvark:latest

RUN $AG install default-jdk git maven tcpdump

WORKDIR /root/

RUN git clone https://github.com/grafnu/mudgee.git && cd mudgee && mvn clean install

COPY misc/test_mudgee .

CMD ./test_mudgee
