# Image name: daq/networking
#
# Image used for host networking services (DNS, DHCP, etc...)
#

FROM daq/aardvark:latest

RUN $AG install dnsmasq ethtool iptables netcat python

RUN echo dhcp-range=10.0.0.128,10.0.0.250,120s >> /etc/dnsmasq.conf

COPY misc/start_networking .

ENTRYPOINT ["./start_networking"]
