FROM daq/aardvark:latest

# Do this alone first so it can be re-used by other build files.
RUN $AG update && $AG install default-jre

RUN $AG update && $AG install default-jdk git

RUN $AG update && $AG install maven tcpdump

WORKDIR /root/

#RUN bin/retry_cmd git clone https://github.com/grafnu/mudgee.git --single-branch --depth 1 \
#  && cd mudgee && ../bin/retry_cmd mvn clean install

COPY misc/test_mudgee .

#CMD ./test_mudgee
CMD true

