## Image name: daq/faucet

FROM faucet/faucet-python3

COPY faucet/ /faucet-src

RUN /faucet-src/docker/base/install-faucet.sh

# Check for target executable since installer doesn't error out properly.
RUN which faucet

CMD ["faucet"]
