## Image name: daq/faucet

FROM faucet/python3

COPY faucet/ /faucet-src/

WORKDIR /faucet-src

RUN ./docker/install-faucet.sh && rm -rf .git

# Check for target executable since installer doesn't error out properly.
RUN which faucet

RUN apk add -q tcpdump iptables

CMD ["faucet"]
