FROM daq/aardvark:latest as bacnet_build

# Do this alone first so it can be re-used for later stages.
RUN $AG update && $AG install default-jre

RUN $AG update && $AG install default-jdk git

RUN git clone https://github.com/grafnu/bacnet4j.git --single-branch --depth 1 \
  && cd bacnet4j && ./gradlew shadow

FROM daq/aardvark:latest

RUN $AG install default-jre

COPY --from=bacnet_build /root/bacnet4j/*.jar bacnet4j/

COPY misc/bacnet_discover .

CMD ["./bacnet_discover"]
