# Image name: daq/networking
#
# Image used for host networking services (DNS, DHCP, etc...)
#

FROM daq/aardvark:latest

RUN $AG install dnsmasq ethtool iptables

RUN echo dhcp-range=10.0.0.128,10.0.0.250,120s >> /etc/dnsmasq.conf

CMD ["dnsmasq", "-d", "--bind-dynamic", "--log-facility=/tmp/dnsmasq.log"]
