FROM daq/aardvark:latest as bacnet_build

RUN $AG install default-jdk git

RUN git clone https://github.com/grafnu/bacnet4j.git --single-branch --depth 1 \
  && cd bacnet4j && ./gradlew shadow

RUN cp bacnet4j/*.jar .

FROM daq/aardvark:latest

RUN $AG install default-jre

COPY --from=bacnet_build /root/*.jar bacnet4j/

COPY misc/bacnet_discover .

CMD ["./bacnet_discover"]
