# Image name: daq/fauxdevice
#
# Faux device for framework development/testing.
#

FROM daq/aardvark:latest

RUN $AG install isc-dhcp-client ethtool network-manager

COPY misc/start_fauxdevice .

CMD ["./start_fauxdevice"]
