# Image name: daq/networking
#
# Image used for host networking services (DNS, DHCP, etc...)
#

FROM daq/aardvark:latest

RUN $AG update && $AG install dnsmasq ethtool iptables netcat python

COPY misc/start_networking .

ENTRYPOINT ["./start_networking"]
