#!/bin/sh -e

dev=$1
addr=$2
addrOnly=${addr%/8}
netmask=

shift || true
shift || true

if [ "$addr" != "$addrOnly" ]; then
  addr=$addrOnly
  netmask="netmask 255.0.0.0"
fi

/sbin/ifconfig $dev $addr $netmask "$@"

