#!/bin/bash -e
source reporting.sh
REPORT=/tmp/report.txt

python dhcp_tests.py connection.ipaddr.dhcp_disconnect
python dhcp_tests.py connection.ipaddr.private_address
python dhcp_tests.py connection.dhcp.ip_change

cat report.txt >> $REPORT
