#!/bin/bash -e
# Continuously monitors dnsmasq config and restarts dnsmasq when config is changed 
config_file='/etc/dnsmasq.conf'
checksum=$(md5sum $config_file | awk '{print $1}')

while true; do
    new_checksum=$(md5sum $config_file | awk '{print $1}')
    if [ $checksum -eq $new_checksum ]; then
        sleep 1
        continue
    fi 
    checksum=$new_checksum
    while [ -z $(cat /var/run/dnsmasq.pid) ]; do
	sleep 1
    done
    kill $(cat /var/run/dnsmasq.pid) || true
    rm -f /var/run/dnsmasq.pid
    dnsmasq --bind-dynamic --log-facility=/tmp/dnsmasq.log --log-dhcp
done
