#!/bin/bash -e
#
# Dynamically change the DHCP response time. Response time of -1 will stop DHCP response
# requires killing and restarting dnsmasq as per documentation 
# (SIGHUP does not reload configuration file).
mac_addr=$1
response_time_sec=$2
if [ -z "$mac_addr" -o -z "$response_time_sec" ]; then
    echo "Usage: ./change_dhcp_response_time mac_addr response_time_sec"
    exit 1
fi

while [ -z $(cat /var/run/dnsmasq.pid) ]; do
    sleep 1
done

dhcp_option="dhcp-host=$mac_addr,ignore"
sed -i s/$dhcp_option// /etc/dnsmasq.conf
echo $dhcp_option >> /etc/dnsmasq.conf

function restart_dnsmasq() {
    kill -9 $(cat /var/run/dnsmasq.pid) || true
    rm -f /var/run/dnsmasq.pid
    dnsmasq --bind-dynamic --log-facility=/tmp/dnsmasq.log --log-dhcp
}

function wait_and_restart_dnsmasq() {
    restart_dnsmasq
    if [ "$response_time_sec" != -1 ]; then
        sleep $response_time_sec
        sed -i s/$dhcp_option// /etc/dnsmasq.conf
        restart_dnsmasq
    fi
}

wait_and_restart_dnsmasq &
sleep 5
