# Image name: daqf/faux
#
# Faux device for framework development/testing.
#

FROM daqf/aardvark:latest

# Run this separately so it can be shared with other builds.
RUN $AG update && $AG install openjdk-11-jre
RUN $AG update && $AG install openjdk-11-jdk git

RUN $AG update && $AG install curl

COPY udmi/schema/ schema/
COPY udmi/gencode gencode/

COPY udmi/validator/ validator/
RUN validator/bin/build

COPY udmi/bin/test_sequencer bin/test_sequencer

COPY subset/cloud/test_udmi .

CMD ./test_udmi
