# Configuration for ATA proxy architecture (working with upstream direct network)

# Load defaults.
include: ${DAQ_LIB}/config/system/default.yaml

# Description for dashboard.
site_description: "ATA Proxy Configuration"

# For large-scale network, no room for sleeping.
settle_sec: 0

# Network switch configuration.
switch_setup:
  model: EXT_STACK
  data_intf: alt-intf
  data_mac: '22:22:22:22:22:22'
  of_dpid: 2
  uplink_port: 7

run_trigger:
  native_vlan: 122
  max_hosts: 3

internal_subnet:
  subnet: 10.21.0.0/16

default_timeout_sec: 120
