---
# Base configuration file for DAQ.
#
# This setup will create and test one faux device. To specify a real USB
# adapter, modify the interfaces entry with the appripriate interface name(s).

# Load defaults.
include: config/system/default.yaml

# Description for dashboard.
site_description: "Baseline Configuration"

# Faux interface devices
interfaces:
  faux:
    opts:
