---
# Base configuration file for DAQ.
#
# This setup will create and test one faux device. To specify a real USB
# adapter, modify the interfaces entry with the appripriate interface name(s).

# Load defaults.
include: default.yaml
host_tests: ${DAQ_LIB}/config/modules/dts.conf

# Description for dashboard.
site_description: "Baseline Configuration"

# Default switch configuration.
switch_setup:
  of_dpid: 2
  uplink_port: 7

# Faux interface devices
interfaces:
  faux:
    opts:
