---
# Base configuration file for DAQ.
#
# This setup will create and test one faux device. To specify a real USB
# adapter, modify the interfaces entry with the appripriate interface name(s).

# Description for dashboard.
site_description: "Default Configuration"

# Default switch configuration.
switch_setup:
  of_dpid: 2
  uplink_port: 7

# Time to let the network settle after some operations.
settle_sec: 5

# Default time to monitor before starting tests.
monitor_scan_sec: 30

# default timeout for tests, or 0 to disable.
default_timeout_sec: 350

# default time between port disconnect and host tests shutdown
port_flap_timeout_sec: 5

# Default base module configuration file.
base_conf: ${DAQ_LIB}/resources/setups/baseline/base_config.json

# Directory of site-configuration data, including devices.
site_path: ${DAQ_CONF}/site/

# DHCP lease time parameters
initial_dhcp_lease_time: 120s
dhcp_lease_time: 500s
long_dhcp_response_sec: 105

# finish hook: executed at the end of every test
finish_hook: ${DAQ_LIB}/bin/dump_network

# topology hook: executed when device topology changes
topology_hook: ${DAQ_LIB}/bin/dump_network

# usi url for DAQ to connect to
usi_setup: 
  url: localhost:5000
  rpc_timeout_sec: 20

# internal test host subnet
internal_subnet:
  subnet: 10.20.0.0/16
