# Dockerfile for running the password test locally and the corresponding faux device.
# Make sure when building this image, the working directory specified in command is DAQ folder.

FROM daqf/aardvark:latest

# Initial dependencies
RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git
RUN $AG update && $AG install python openssl ssh nmap

# Get password test dependencies
RUN $AG update && $AG install curl
RUN $AG update && $AG install ncrack hydra

# Setup source folder in container
COPY subset/security .
RUN cd security_passwords && ./gradlew shadowJar

# Run the pass test -> May have to adjust the IP addresses from time to time.
CMD ["security_passwords/src/main/test_docker_files/run_password_tests.sh", \
  "172.17.0.2", "172.17.0.3", "172.17.0.4", "02:42:ac:11:00:02", "02:42:ac:11:00:03", \
  "02:42:ac:11:00:04"]
