#!/bin/bash -e
source reporting.sh
REPORT=/tmp/report.txt
LOCAL_REPORT=tmp/report.txt
MANIFEST=./switches/module_manifest.json
MONO_LOG=/tmp/monolog.switch.txt
RESULT_LINES=/tmp/results.switch.txt
MODULE_CONFIG=/config/device/module_config.json

route add default gw $GATEWAY_IP
ping -c 2 $GATEWAY_IP
# Setup for accessing control plane switch. If LOCAL_IP is defined, which
# is the intended local address for this node on the control plane then
# SWITCH_IP will be the IP address of the OpenFlow switch.

if [ -n "$LOCAL_IP" ]; then
    USI_URL=`jq -r .run_info.usi.url $MODULE_CONFIG`
    RPC_TIMEOUT=`jq -r .run_info.usi.rpc_timeout_sec $MODULE_CONFIG` || 10
    SWITCH_IP=`jq -r .run_info.switch.ip $MODULE_CONFIG`
    SWITCH_MODEL=`jq -r .run_info.switch.model $MODULE_CONFIG`
    SWITCH_USERNAME=`jq -r .run_info.switch.username $MODULE_CONFIG`
    SWITCH_PASSWORD=`jq -r .run_info.switch.password $MODULE_CONFIG`

    echo Configuring network with local address $LOCAL_IP.
    ip addr add $LOCAL_IP dev `hostname`-eth0
    echo Switch test with model $SWITCH_MODEL
    echo Switch test with ip:port $SWITCH_IP:$TARGET_PORT
    echo Switch test with username:password $SWITCH_USERNAME:$SWITCH_PASSWORD
    # It may take up to 40 pings for it to go through for Cisco switch. Root cause is still unknown atm.
    ping -n -c 100 $SWITCH_IP
    POE_ENABLED=`jq -r .modules.switch.poe.enabled $MODULE_CONFIG`
    java -jar switches/target/switchtest-0.0.1-jar-with-dependencies.jar $USI_URL $RPC_TIMEOUT $SWITCH_IP $TARGET_PORT $POE_ENABLED $SWITCH_MODEL $SWITCH_USERNAME $SWITCH_PASSWORD

    grep -v "RESULT" $LOCAL_REPORT | tee -a $MONO_LOG
    grep "RESULT" $LOCAL_REPORT | tee -a $RESULT_LINES

    write_out_monolog $REPORT \
                      $MANIFEST \
                      $MONO_LOG \
                      $RESULT_LINES
 
else

    SKIP_REASON="LOCAL_IP not configured, assuming no network switch."
    RESULT="skip"
    SUMMARY="No local IP has been set, check system config"

    write_out_result $REPORT \
                     "connection.switch.port_link" \
                     "$(jq -r '.["connection.switch.port_link"].description' $MANIFEST)" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.switch.port_link $SUMMARY"

    write_out_result $REPORT \
                     "connection.switch.port_speed" \
                     "$(jq -r '.["connection.switch.port_speed"].description' $MANIFEST)" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.switch.port_speed $SUMMARY"

    write_out_result $REPORT \
                     "connection.switch.port_duplex" \
                     "$(jq -r '.["connection.switch.port_duplex"].description' $MANIFEST)" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT connection.switch.port_duplex $SUMMARY"

    write_out_result $REPORT \
                     "poe.switch.power" \
                     "$(jq -r '.["poe.switch.power"].description' $MANIFEST)" \
                     "$SKIP_REASON" \
                     "RESULT $RESULT poe.switch.power $SUMMARY"

fi
