#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT

INSTDIR=${1:-inst}

CMDIN=$INSTDIR/daq_cmd.in
CMDOUT=$INSTDIR/daq_cmd.out

rm -f $CMDIN $CMDOUT
touch $CMDIN

echo Processing commands from $CMDIN to $CMDOUT

tail -f $CMDIN < /dev/null | awk '{print "\""$0"\""; fflush() }' | xargs -L 1 bash -c > $CMDOUT 2>&1

echo Done with cmd processor.
