#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT

INSTDIR=${1:-inst}

CMDSOCK=$INSTDIR/daq_cmd.sock
CMDOUT=$INSTDIR/daq_cmd.out

rm -f $CMDSOCK $CMDOUT

echo Processing commands from $CMDSOCK to $CMDOUT

export PS1=
export TERM=dumb

ncat -U -k -l $CMDSOCK < /dev/null | xargs -L 1 bash --norc -c > $CMDOUT 2>&1

echo Done with cmd processor.
