#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
INSTDIR=$ROOT/inst
IMAGE=daq/runner

if [ "$1" == base ]; then
    IMAGE=daq/base
    base_flags="-v $ROOT/build:/build"
    shift
fi

sudo rm -rf $INSTDIR
mkdir -p $INSTDIR

docker rm -f daq-runner > /dev/null 2>&1 || true

docker run --privileged --name daq-runner --env DAQ_CONTAINER=daq/runner $base_flags -v $INSTDIR:/root/daq/inst -ti $IMAGE "$@"
