#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
INSTDIR=$ROOT/inst

rm -rf $INSTDIR
mkdir -p $INSTDIR

$ROOT/cmd/faucet

$ROOT/cmd/cmdserver $INSTDIR

docker run --privileged -v $INSTDIR:/root/daq/inst -ti daq/runner
