#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
INSTDIR=$ROOT/inst
FAUCET_SOCK=faucet_event.sock
EVENT_SOCK=$INSTDIR/$FAUCET_SOCK
SYSTEM_CONF=system.conf
LOCAL_CONFIG=local/$SYSTEM_CONF

cd $ROOT

FAUCET=$(realpath $ROOT/faucet)

if [ -n "$DAQ_CONTAINER" ]; then
    echo Replacing $LOCAL_CONFIG with version from $INSTDIR...
    rm -f $LOCAL_CONFIG
    mkdir -p local
    test -f $INSTDIR/$SYSTEM_CONF && cp $INSTDIR/$SYSTEM_CONF $LOCAL_CONFIG
fi

if [ -f $LOCAL_CONFIG ]; then
    echo Loading daq run configuration from $LOCAL_CONFIG
    source $LOCAL_CONFIG
fi

if [ ! -d $FAUCET ]; then
    echo Faucet directory $FAUCET not found.
    false
fi

mkdir -p $INSTDIR
rm -f $EVENT_SOCK

docker ps > /dev/null 2>&1 || service docker start

ovsctl=/usr/share/openvswitch/scripts/ovs-ctl
$ovsctl status || sudo $ovsctl start

if [ -z "$daq_intf" ]; then
    echo Setting daq_intf not defined, defaulting to auto-start faux device.
    daq_intf="faux!"
fi

intfs=$(echo $daq_intf | tr , ' ')
nintf=
for intf in $intfs; do
    if [ "$intf" == "local!" ]; then
        intf=local
        echo Implicitly running local device...
        $ROOT/cmd/local
        cleanup="$ROOT/cmd/local clean"
    fi

    if [ "$intf" == "faux!" ]; then
        intf=faux
        echo Implicitly running faux device...
        $ROOT/cmd/faux
        cleanup="echo Killing daq-faux container...; docker kill daq-faux > /dev/null"
    fi

    ip addr show $intf || true
    nintf+=",$intf"

    # If running inside of a container, wait until the host test interface shows up...
    if [ -n "$DAQ_CONTAINER" -a -z "$cleanup" ]; then
        while ! ifconfig -a | fgrep -q $intf; do
            echo Waiting for interface $intf to appear...
            sleep 1
        done
    fi
done
daq_intf=${nintf#,}

runcmd=python
if [ -f .pdbrc ]; then
    echo Found .pdbrc file, using pdb...
    runcmd=pdb
fi

export PYTHONDONTWRITEBYTECODE=1

echo Executing runner "$@"...

sudo env \
     DAQ_CONTAINER=$DAQ_CONTAINER \
     FAUCET_EVENT_SOCK=$EVENT_SOCK \
     PYTHONPATH=$FAUCET \
     DOCKER_STARTUP_TIMEOUT_MS=$DOCKER_STARTUP_TIMEOUT_MS \
     TERM=dumb $runcmd daq/daq.py $LOCAL_CONFIG "$@"

if [ -n "$cleanup" ]; then
    sh -c "$cleanup"
fi

echo Done with run.
