#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
INSTDIR=$ROOT/inst
IMAGE=daq/faux
local_config=$ROOT/local/system.conf
postfix=
intf_mac=9a:02:57:1e:8f:00

cd $ROOT
source misc/config_base.sh

# If the argument starts with a :, then it's an interface name.
if [ "${1#:}" != "$1" ]; then
    realintf=${1#:}
    postfix=-$realintf
    echo Running using interface $realintf
    shift
fi

# If the first argument is a number, then it's a port designation.
if [ $# -gt 0 -a $(($1)) -gt 0 ]; then
    port_num=$1
    postfix=-$port_num
    intf_mac=9a:02:57:1e:8f:0$port_num
    shift
fi

FAUX_ARGS="$*"

CONTAINER=daq-faux$postfix

if [ -z "$FAUX_ARGS" ]; then
    FAUX_ARGS="$faux_args"
fi

echo Launching faux $FAUX_ARGS...

if docker container inspect $CONTAINER --format '{{ .Name }}' > /dev/null 2>&1; then
    echo -n "Clensing old container "
    docker rm -f $CONTAINER
fi

FAUXTMP=$INSTDIR/faux/$CONTAINER/tmp
sudo rm -rf $FAUXTMP
sudo mkdir -p $FAUXTMP

docker_args="-v $FAUXTMP:/tmp"

CONFIG_DIR=$ROOT/${test_config%/}/$CONTAINER
if [ -d "$CONFIG_DIR" ]; then
    echo Mapping config dir $CONFIG_DIR...
    docker_args="$docker_args -v $CONFIG_DIR:/config"
elif [ -n "$test_config" ]; then
    echo Config dir $CONFIG_DIR not found.
fi

cid=$(docker run -d --privileged --name $CONTAINER --hostname $CONTAINER --net=none $docker_args $IMAGE $FAUX_ARGS)
pid=$(docker inspect --format="{{ .State.Pid }}" $cid)

echo DAQ autoclean docker kill $CONTAINER

if [ -n "$realintf" ]; then
    echo Moving $realintf into $pid...
    sudo ip link set $realintf netns $pid
    docker exec $CONTAINER ip link set $realintf up
    docker exec $CONTAINER ip link show $realintf
else
    intf=faux$postfix
    echo Removing old interface $intf
    sudo ip link del $intf 2>/dev/null || true

    echo Adding new interface to $pid...
    sudo ip link add $intf type veth peer name faux-eth0 addr $intf_mac netns $pid
    sudo ip link set $intf up
fi

echo Done with faux device launch.
