#!/bin/bash -e

ROOT=$(dirname $0)/..
local_config=local/system.conf
build_root=build
build_args=

cd $ROOT
source misc/config_base.sh

if [ "$1" == skip ]; then
    build_extra=skip
    run_extra=skip
else
    build_extra=save
    run_extra=load
fi

cmd/build $build_extra

file=misc/Dockerfile.base
target=daq/base
mkdir -p $build_root
logfile=$build_root/docker_build.base
echo Building $file into $target, log to $logfile...

failed=
docker build -t $target $build_args -f $file . > $logfile 2>&1 || failed=y
if [ -n "$failed" ]; then
    tail $logfile
    false
fi

images=$(docker images | fgrep daq/ | awk '{print $1}')

# Force because inbuild implies release version, not local.
run_mode=$(cat misc/RELEASE_VERSION)

echo Runner build on top of base...

# Explicilty run in /daq not /root/daq because of volume mapping.
echo cmd/run run_mode=base run_cmd=/daq/cmd/build run_extra=$run_extra
cmd/run run_mode=base run_cmd=/daq/cmd/build run_extra=$run_extra

if [ -n "$CONTINUOUS_INTEGRATION" ]; then
    echo Skipping container commit since its too intensive for automatic builds.
else
    echo Committing runner container image to daqf/runner...
    docker commit -c 'ENTRYPOINT ["/root/daq/cmd/exrun"]' daq-runner daqf/runner > /dev/null
fi
