#!/bin/bash -e

# Set so pipe through tee will fail.
set -o pipefail

ROOT=$(realpath $(dirname $0)/..)
run_args="$@"
cmdrun_log=inst/cmdrun.log

cd $ROOT
source misc/config_base.sh

echo Starting `date`
echo Clearing previous state...
sudo rm -rf inst/reports inst/run-port-* $cmdrun_log
sudo chown -f $USER -R inst || true

if [ -n "$build_tests" ]; then
    cmd/build check
fi

bin/build_hash check

if [ -f "$gcp_cred" ]; then
    echo Installing $gcp_cred into inst/config...
    gcp_target=inst/config/gcp_service_account.json
    if ! diff $gcp_cred $gcp_target; then
        cp $gcp_cred inst/config/gcp_service_account.json
    fi
fi

cmd/exrun $run_args 2>&1 | tee $cmdrun_log
