#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
run_args=
cmdrun_log=inst/cmdrun.log

cd $ROOT
source misc/config_base.sh

if [ "${1#run_mode=}" != "$1" ]; then
    run_mode=${1#run_mode=}
    shift
fi

if [ "$run_mode" == "latest" ]; then
    run_args=latest
fi

if [ -z "$run_mode" ]; then
    echo run_mode not defined.
    false
fi

test -f .build_hash || touch .build_hash
build_hash=$(bin/build_hash.sh)
local_hash=$(< .build_hash)
if [ "$build_hash" != "$local_hash" ]; then
    echo Local build hash does not match, or not found.
    echo Please run cmd/build, or if you know what you\'re doing:
    echo echo $build_hash \> .build_hash
    if [ -f .build_built ]; then
        echo Output of: diff .build_built .build_files
        diff .build_built .build_files || true
    fi
    false
fi

echo Starting `date`, run_mode is $run_mode
echo Clearing previous reports...
sudo rm -rf inst/report_*.txt inst/run-port-* $cmdrun_log
mkdir -p inst

if [ "$run_mode" == local ]; then
    cmd/exrun $run_args "$@" 2>&1 | tee $cmdrun_log
else
    cmd/inrun $run_args "$@" 2>&1 | tee $cmdrun_log
fi
