#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)

FAUCET=$(realpath $ROOT/../faucet)

if [ ! -d $FAUCET ]; then
    echo Faucet directory $FAUCET not found.
    false
fi

cd $ROOT

ovsctl=/usr/share/openvswitch/scripts/ovs-ctl
$ovsctl status || sudo $ovsctl start

sudo DAQ_CONTAINER=$DAQ_CONTAINER PYTHONPATH=$FAUCET TERM=dumb python daq/daq.py
