#!/bin/bash -e

ROOT=$(realpath $(dirname $0)/..)
USI_DIR=$ROOT/inst/network
DEBUG=""

debug_mode="true" #Always in debug mode for now
if [ -n $debug_mode ]; then
    DEBUG="debug"
    echo Starting USI in debug mode
else
    echo Starting USI
fi

rm -rf $USI_DIR
mkdir -p $USI_DIR
GOOGLE_APPLICATION_CREDENTIALS=$gcp_cred docker run -d -v $USI_DIR:/ovs --privileged --network=host -e DEBUG=$DEBUG --name daq-usi daqf/usi

echo DAQ autoclean docker cp daq-usi:/root/logs.txt inst/usi-logs.txt
echo DAQ autoclean docker kill daq-usi 
