version: '2'

services:
    wpasupplicant:
        build:
            context: ../..
            dockerfile: ./docker/modules/Dockerfile.faux1
        image: 'authenticator/wpasupplicant:latest'
        depends_on: [authenticator]
        #command: bash -c "wpa_supplicant -dd -c/tmp/wpasupplicant/wired-peap.conf -ieth0 -Dwired"
        networks:
            00wpasupplicant-net:
                ipv4_address: 10.20.0.11
        cap_add:
            - ALL
        volumes:
            - ../../docker/include/etc/wpasupplicant/:/tmp/wpasupplicant/
            - ../../docker/include/etc/wpasupplicant/cert/:/tmp/cert/

    authenticator:
        build:
            context: ../..
            dockerfile: ./subset/dot1x/Dockerfile.test_dot1x
        image: 'authenticator/authenticator:latest'
        #command: tail -f
        networks:
            00wpasupplicant-net:
                ipv4_address: 10.20.0.3
                priority: 200
        cap_add:
            - ALL

    tcpdump:
        image: kaazing/tcpdump
        network_mode: "host"
        volumes:
            - ./tcpdump:/tcpdump

networks:
    00wpasupplicant-net:
        driver: macvlan
        ipam:
            config:
                - subnet: 10.20.0.0/16
