FROM daqf/aardvark:latest

RUN apt-get update && \
    apt-get install -y freeradius git gcc python3-dev musl-dev g++

COPY subset/dot1x/ .

EXPOSE \
    1812/udp \
    1813/udp \
    18120

CMD ["./test_dot1x"]
