version: '2'

services:
    wpasupplicant:
        build:
            context: ../../docker/modules/
            dockerfile: Dockerfile.wpasupplicant
        image: 'authenticator/wpasupplicant:latest'
        depends_on: [authenticator]
        command: bash -c "wpa_supplicant -dd -c/tmp/wpasupplicant/wired-peap.conf -ieth0 -Dwired"
        networks:
            00wpasupplicant-net:
                ipv4_address: 172.23.0.111
        cap_add:
            - ALL
        volumes:
            - ../../etc/wpasupplicant/:/tmp/wpasupplicant/
            - ../../etc/wpasupplicant/cert/:/tmp/cert/

    authenticator:
        build:
            context: .
            dockerfile: Dockerfile.authenticator
        image: 'authenticator/authenticator:latest'
        #command: ./start_radius_and_auth
        networks:
            00wpasupplicant-net:
                ipv4_address: 172.23.0.112
                priority: 200
        cap_add:
            - ALL
        volumes:
            - ./:/authenticator-src/
            - "./freeradius/users:/etc/freeradius/3.0/users:ro"
            - "./freeradius/certs:/etc/freeradius/3.0/certs"
            - "./freeradius/default/eap:/etc/freeradius/3.0/mods-enabled/eap:ro"
            - "./freeradius/clients.conf:/etc/freeradius/3.0/clients.conf:ro"

    tcpdump:
        image: kaazing/tcpdump
        network_mode: "host"
        volumes:
            - ./tcpdump:/tcpdump

networks:
    00wpasupplicant-net:
        driver: macvlan
        ipam:
            config:
                - subnet: 172.23.0.0/16
