FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y freeradius iproute2 vim

USER freerad:freerad

EXPOSE \
    1812/udp \
    1813/udp \
    18120

CMD ["freeradius", "-fxx", "-l", "stdout"]
