#!/bin/bash -e

LOCAL_IF=${LOCAL_IF:-$HOSTNAME-eth0}
EXT_IF=eth0

function finished {
    echo networking container terminating
}
trap finished EXIT

echo Starting networking for $LOCAL_IF and $EXT_IF

while ! ifconfig -a | fgrep -q $LOCAL_IF; do
    echo Waiting for interface $LOCAL_IF to exist...
    sleep 1
done

# Pick a random DHCP range to force clients to pick a new address.
subnet=$((RANDOM % 99 + 1))
echo Configuring with subnet 10.20.$subnet.XX
echo dhcp-range=10.20.$subnet.100,10.20.$subnet.254 >> /etc/dnsmasq.conf

# Use ourself as the DNS and NTP server explicitly specified
ip addr add 10.20.$subnet.2 dev $LOCAL_IF
echo dhcp-option=6,10.20.$subnet.2 >> /etc/dnsmasq.conf
echo dhcp-option=42,10.20.$subnet.2 >> /etc/dnsmasq.conf

if ! ip addr show dev $LOCAL_IF | fgrep -q 'inet '; then
  echo Assigning gateway address 10.20.$subnet.1/16
  ip addr add 10.20.$subnet.1/16 dev $LOCAL_IF
fi

echo dhcp-host=*,ignore >> /etc/dnsmasq.conf

# Start the NTP server
service ntp start

echo Blocking for all eternity.
./autorestart_dnsmasq
