# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/acl_counts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/acl_counts.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x64\x61q/proto/acl_counts.proto\"\x9c\x02\n\tAclCounts\x12(\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x17.AclCounts.DevicesEntry\x1a\x43\n\x0c\x44\x65vicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.AclCounts.AclCount:\x02\x38\x01\x1a}\n\x08\x41\x63lCount\x12-\n\x05rules\x18\x01 \x03(\x0b\x32\x1e.AclCounts.AclCount.RulesEntry\x1a\x42\n\nRulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.AclCounts.RuleCount:\x02\x38\x01\x1a!\n\tRuleCount\x12\x14\n\x0cpacket_count\x18\x01 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACLCOUNTS_DEVICESENTRY = _descriptor.Descriptor(
  name='DevicesEntry',
  full_name='AclCounts.DevicesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AclCounts.DevicesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='AclCounts.DevicesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=153,
)

_ACLCOUNTS_ACLCOUNT_RULESENTRY = _descriptor.Descriptor(
  name='RulesEntry',
  full_name='AclCounts.AclCount.RulesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AclCounts.AclCount.RulesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='AclCounts.AclCount.RulesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=280,
)

_ACLCOUNTS_ACLCOUNT = _descriptor.Descriptor(
  name='AclCount',
  full_name='AclCounts.AclCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='AclCounts.AclCount.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACLCOUNTS_ACLCOUNT_RULESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=280,
)

_ACLCOUNTS_RULECOUNT = _descriptor.Descriptor(
  name='RuleCount',
  full_name='AclCounts.RuleCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_count', full_name='AclCounts.RuleCount.packet_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=315,
)

_ACLCOUNTS = _descriptor.Descriptor(
  name='AclCounts',
  full_name='AclCounts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='AclCounts.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACLCOUNTS_DEVICESENTRY, _ACLCOUNTS_ACLCOUNT, _ACLCOUNTS_RULECOUNT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=315,
)

_ACLCOUNTS_DEVICESENTRY.fields_by_name['value'].message_type = _ACLCOUNTS_ACLCOUNT
_ACLCOUNTS_DEVICESENTRY.containing_type = _ACLCOUNTS
_ACLCOUNTS_ACLCOUNT_RULESENTRY.fields_by_name['value'].message_type = _ACLCOUNTS_RULECOUNT
_ACLCOUNTS_ACLCOUNT_RULESENTRY.containing_type = _ACLCOUNTS_ACLCOUNT
_ACLCOUNTS_ACLCOUNT.fields_by_name['rules'].message_type = _ACLCOUNTS_ACLCOUNT_RULESENTRY
_ACLCOUNTS_ACLCOUNT.containing_type = _ACLCOUNTS
_ACLCOUNTS_RULECOUNT.containing_type = _ACLCOUNTS
_ACLCOUNTS.fields_by_name['devices'].message_type = _ACLCOUNTS_DEVICESENTRY
DESCRIPTOR.message_types_by_name['AclCounts'] = _ACLCOUNTS

AclCounts = _reflection.GeneratedProtocolMessageType('AclCounts', (_message.Message,), dict(

  DevicesEntry = _reflection.GeneratedProtocolMessageType('DevicesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ACLCOUNTS_DEVICESENTRY,
    __module__ = 'daq.proto.acl_counts_pb2'
    # @@protoc_insertion_point(class_scope:AclCounts.DevicesEntry)
    ))
  ,

  AclCount = _reflection.GeneratedProtocolMessageType('AclCount', (_message.Message,), dict(

    RulesEntry = _reflection.GeneratedProtocolMessageType('RulesEntry', (_message.Message,), dict(
      DESCRIPTOR = _ACLCOUNTS_ACLCOUNT_RULESENTRY,
      __module__ = 'daq.proto.acl_counts_pb2'
      # @@protoc_insertion_point(class_scope:AclCounts.AclCount.RulesEntry)
      ))
    ,
    DESCRIPTOR = _ACLCOUNTS_ACLCOUNT,
    __module__ = 'daq.proto.acl_counts_pb2'
    # @@protoc_insertion_point(class_scope:AclCounts.AclCount)
    ))
  ,

  RuleCount = _reflection.GeneratedProtocolMessageType('RuleCount', (_message.Message,), dict(
    DESCRIPTOR = _ACLCOUNTS_RULECOUNT,
    __module__ = 'daq.proto.acl_counts_pb2'
    # @@protoc_insertion_point(class_scope:AclCounts.RuleCount)
    ))
  ,
  DESCRIPTOR = _ACLCOUNTS,
  __module__ = 'daq.proto.acl_counts_pb2'
  # @@protoc_insertion_point(class_scope:AclCounts)
  ))
_sym_db.RegisterMessage(AclCounts)
_sym_db.RegisterMessage(AclCounts.DevicesEntry)
_sym_db.RegisterMessage(AclCounts.AclCount)
_sym_db.RegisterMessage(AclCounts.AclCount.RulesEntry)
_sym_db.RegisterMessage(AclCounts.RuleCount)


_ACLCOUNTS_DEVICESENTRY.has_options = True
_ACLCOUNTS_DEVICESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_ACLCOUNTS_ACLCOUNT_RULESENTRY.has_options = True
_ACLCOUNTS_ACLCOUNT_RULESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
