# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/acl_counts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/acl_counts.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x64\x61q/proto/acl_counts.proto\"p\n\tAclCounts\x12(\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x17.AclCounts.DevicesEntry\x1a\x39\n\x0c\x44\x65vicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.AclCount:\x02\x38\x01\"y\n\x08\x41\x63lCount\x12#\n\x05rules\x18\x01 \x03(\x0b\x32\x14.AclCount.RulesEntry\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\x1a\x38\n\nRulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.RuleCount:\x02\x38\x01\"!\n\tRuleCount\x12\x14\n\x0cpacket_count\x18\x01 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACLCOUNTS_DEVICESENTRY = _descriptor.Descriptor(
  name='DevicesEntry',
  full_name='AclCounts.DevicesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AclCounts.DevicesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='AclCounts.DevicesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=142,
)

_ACLCOUNTS = _descriptor.Descriptor(
  name='AclCounts',
  full_name='AclCounts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='AclCounts.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACLCOUNTS_DEVICESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=142,
)


_ACLCOUNT_RULESENTRY = _descriptor.Descriptor(
  name='RulesEntry',
  full_name='AclCount.RulesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AclCount.RulesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='AclCount.RulesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=265,
)

_ACLCOUNT = _descriptor.Descriptor(
  name='AclCount',
  full_name='AclCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='AclCount.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errors', full_name='AclCount.errors', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACLCOUNT_RULESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=265,
)


_RULECOUNT = _descriptor.Descriptor(
  name='RuleCount',
  full_name='RuleCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet_count', full_name='RuleCount.packet_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=300,
)

_ACLCOUNTS_DEVICESENTRY.fields_by_name['value'].message_type = _ACLCOUNT
_ACLCOUNTS_DEVICESENTRY.containing_type = _ACLCOUNTS
_ACLCOUNTS.fields_by_name['devices'].message_type = _ACLCOUNTS_DEVICESENTRY
_ACLCOUNT_RULESENTRY.fields_by_name['value'].message_type = _RULECOUNT
_ACLCOUNT_RULESENTRY.containing_type = _ACLCOUNT
_ACLCOUNT.fields_by_name['rules'].message_type = _ACLCOUNT_RULESENTRY
DESCRIPTOR.message_types_by_name['AclCounts'] = _ACLCOUNTS
DESCRIPTOR.message_types_by_name['AclCount'] = _ACLCOUNT
DESCRIPTOR.message_types_by_name['RuleCount'] = _RULECOUNT

AclCounts = _reflection.GeneratedProtocolMessageType('AclCounts', (_message.Message,), dict(

  DevicesEntry = _reflection.GeneratedProtocolMessageType('DevicesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ACLCOUNTS_DEVICESENTRY,
    __module__ = 'daq.proto.acl_counts_pb2'
    # @@protoc_insertion_point(class_scope:AclCounts.DevicesEntry)
    ))
  ,
  DESCRIPTOR = _ACLCOUNTS,
  __module__ = 'daq.proto.acl_counts_pb2'
  # @@protoc_insertion_point(class_scope:AclCounts)
  ))
_sym_db.RegisterMessage(AclCounts)
_sym_db.RegisterMessage(AclCounts.DevicesEntry)

AclCount = _reflection.GeneratedProtocolMessageType('AclCount', (_message.Message,), dict(

  RulesEntry = _reflection.GeneratedProtocolMessageType('RulesEntry', (_message.Message,), dict(
    DESCRIPTOR = _ACLCOUNT_RULESENTRY,
    __module__ = 'daq.proto.acl_counts_pb2'
    # @@protoc_insertion_point(class_scope:AclCount.RulesEntry)
    ))
  ,
  DESCRIPTOR = _ACLCOUNT,
  __module__ = 'daq.proto.acl_counts_pb2'
  # @@protoc_insertion_point(class_scope:AclCount)
  ))
_sym_db.RegisterMessage(AclCount)
_sym_db.RegisterMessage(AclCount.RulesEntry)

RuleCount = _reflection.GeneratedProtocolMessageType('RuleCount', (_message.Message,), dict(
  DESCRIPTOR = _RULECOUNT,
  __module__ = 'daq.proto.acl_counts_pb2'
  # @@protoc_insertion_point(class_scope:RuleCount)
  ))
_sym_db.RegisterMessage(RuleCount)


_ACLCOUNTS_DEVICESENTRY.has_options = True
_ACLCOUNTS_DEVICESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_ACLCOUNT_RULESENTRY.has_options = True
_ACLCOUNT_RULESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
