# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daq/proto/system_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daq/proto/system_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x64\x61q/proto/system_state.proto\"N\n\x0bRunnerState\x1a?\n\x08PortInfo\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x16\n\x0e\x66lapping_start\x18\x02 \x01(\x02\x12\x0b\n\x03mac\x18\x03 \x01(\tb\x06proto3')
)




_RUNNERSTATE_PORTINFO = _descriptor.Descriptor(
  name='PortInfo',
  full_name='RunnerState.PortInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='RunnerState.PortInfo.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flapping_start', full_name='RunnerState.PortInfo.flapping_start', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='RunnerState.PortInfo.mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=110,
)

_RUNNERSTATE = _descriptor.Descriptor(
  name='RunnerState',
  full_name='RunnerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_RUNNERSTATE_PORTINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=110,
)

_RUNNERSTATE_PORTINFO.containing_type = _RUNNERSTATE
DESCRIPTOR.message_types_by_name['RunnerState'] = _RUNNERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunnerState = _reflection.GeneratedProtocolMessageType('RunnerState', (_message.Message,), dict(

  PortInfo = _reflection.GeneratedProtocolMessageType('PortInfo', (_message.Message,), dict(
    DESCRIPTOR = _RUNNERSTATE_PORTINFO,
    __module__ = 'daq.proto.system_state_pb2'
    # @@protoc_insertion_point(class_scope:RunnerState.PortInfo)
    ))
  ,
  DESCRIPTOR = _RUNNERSTATE,
  __module__ = 'daq.proto.system_state_pb2'
  # @@protoc_insertion_point(class_scope:RunnerState)
  ))
_sym_db.RegisterMessage(RunnerState)
_sym_db.RegisterMessage(RunnerState.PortInfo)


# @@protoc_insertion_point(module_scope)
