# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import usi_pb2 as proto_dot_usi__pb2


class USIServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPower = channel.unary_unary(
        '/usi.USIService/GetPower',
        request_serializer=proto_dot_usi__pb2.SwitchInfo.SerializeToString,
        response_deserializer=proto_dot_usi__pb2.PowerResponse.FromString,
        )
    self.GetInterface = channel.unary_unary(
        '/usi.USIService/GetInterface',
        request_serializer=proto_dot_usi__pb2.SwitchInfo.SerializeToString,
        response_deserializer=proto_dot_usi__pb2.InterfaceResponse.FromString,
        )
    self.disconnect = channel.unary_unary(
        '/usi.USIService/disconnect',
        request_serializer=proto_dot_usi__pb2.SwitchInfo.SerializeToString,
        response_deserializer=proto_dot_usi__pb2.SwitchActionResponse.FromString,
        )
    self.connect = channel.unary_unary(
        '/usi.USIService/connect',
        request_serializer=proto_dot_usi__pb2.SwitchInfo.SerializeToString,
        response_deserializer=proto_dot_usi__pb2.SwitchActionResponse.FromString,
        )


class USIServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInterface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def disconnect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_USIServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPower': grpc.unary_unary_rpc_method_handler(
          servicer.GetPower,
          request_deserializer=proto_dot_usi__pb2.SwitchInfo.FromString,
          response_serializer=proto_dot_usi__pb2.PowerResponse.SerializeToString,
      ),
      'GetInterface': grpc.unary_unary_rpc_method_handler(
          servicer.GetInterface,
          request_deserializer=proto_dot_usi__pb2.SwitchInfo.FromString,
          response_serializer=proto_dot_usi__pb2.InterfaceResponse.SerializeToString,
      ),
      'disconnect': grpc.unary_unary_rpc_method_handler(
          servicer.disconnect,
          request_deserializer=proto_dot_usi__pb2.SwitchInfo.FromString,
          response_serializer=proto_dot_usi__pb2.SwitchActionResponse.SerializeToString,
      ),
      'connect': grpc.unary_unary_rpc_method_handler(
          servicer.connect,
          request_deserializer=proto_dot_usi__pb2.SwitchInfo.FromString,
          response_serializer=proto_dot_usi__pb2.SwitchActionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'usi.USIService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
