# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import usi_pb2 as usi__pb2


class USIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPower = channel.unary_unary(
                '/usi.USIService/GetPower',
                request_serializer=usi__pb2.SwitchInfo.SerializeToString,
                response_deserializer=usi__pb2.PowerResponse.FromString,
                )
        self.GetInterface = channel.unary_unary(
                '/usi.USIService/GetInterface',
                request_serializer=usi__pb2.SwitchInfo.SerializeToString,
                response_deserializer=usi__pb2.InterfaceResponse.FromString,
                )
        self.disconnect = channel.unary_unary(
                '/usi.USIService/disconnect',
                request_serializer=usi__pb2.SwitchInfo.SerializeToString,
                response_deserializer=usi__pb2.SwitchActionResponse.FromString,
                )
        self.connect = channel.unary_unary(
                '/usi.USIService/connect',
                request_serializer=usi__pb2.SwitchInfo.SerializeToString,
                response_deserializer=usi__pb2.SwitchActionResponse.FromString,
                )


class USIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_USIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPower,
                    request_deserializer=usi__pb2.SwitchInfo.FromString,
                    response_serializer=usi__pb2.PowerResponse.SerializeToString,
            ),
            'GetInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterface,
                    request_deserializer=usi__pb2.SwitchInfo.FromString,
                    response_serializer=usi__pb2.InterfaceResponse.SerializeToString,
            ),
            'disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.disconnect,
                    request_deserializer=usi__pb2.SwitchInfo.FromString,
                    response_serializer=usi__pb2.SwitchActionResponse.SerializeToString,
            ),
            'connect': grpc.unary_unary_rpc_method_handler(
                    servicer.connect,
                    request_deserializer=usi__pb2.SwitchInfo.FromString,
                    response_serializer=usi__pb2.SwitchActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usi.USIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class USIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usi.USIService/GetPower',
            usi__pb2.SwitchInfo.SerializeToString,
            usi__pb2.PowerResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usi.USIService/GetInterface',
            usi__pb2.SwitchInfo.SerializeToString,
            usi__pb2.InterfaceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usi.USIService/disconnect',
            usi__pb2.SwitchInfo.SerializeToString,
            usi__pb2.SwitchActionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/usi.USIService/connect',
            usi__pb2.SwitchInfo.SerializeToString,
            usi__pb2.SwitchActionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
