# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usi.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usi.proto',
  package='usi',
  syntax='proto3',
  serialized_options=b'\n\004grpcB\010USIProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tusi.proto\x12\x03usi\"\'\n\x14SwitchActionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x9b\x01\n\rPowerResponse\x12!\n\x19\x63urrent_power_consumption\x18\x01 \x01(\x02\x12\x1d\n\x15max_power_consumption\x18\x02 \x01(\x02\x12$\n\x0bpoe_support\x18\x03 \x01(\x0e\x32\x0f.usi.POESupport\x12\"\n\npoe_status\x18\x04 \x01(\x0e\x32\x0e.usi.POEStatus\"]\n\x11InterfaceResponse\x12$\n\x0blink_status\x18\x01 \x01(\x0e\x32\x0f.usi.LinkStatus\x12\x12\n\nlink_speed\x18\x02 \x01(\x05\x12\x0e\n\x06\x64uplex\x18\x03 \x01(\t\"w\n\nSwitchInfo\x12\x0f\n\x07ip_addr\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_port\x18\x03 \x01(\x05\x12\x1f\n\x05model\x18\x04 \x01(\x0e\x32\x10.usi.SwitchModel\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t*F\n\x0bSwitchModel\x12\x17\n\x13\x41LLIED_TELESIS_X230\x10\x00\x12\x0e\n\nCISCO_9300\x10\x01\x12\x0e\n\nOVS_SWITCH\x10\x02*\x1e\n\nLinkStatus\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01*\'\n\nPOESupport\x12\x0b\n\x07\x45NABLED\x10\x00\x12\x0c\n\x08\x44ISABLED\x10\x01*1\n\tPOEStatus\x12\x06\n\x02ON\x10\x00\x12\x07\n\x03OFF\x10\x01\x12\t\n\x05\x46\x41ULT\x10\x02\x12\x08\n\x04\x44\x45NY\x10\x03\x32\xef\x01\n\nUSIService\x12\x31\n\x08GetPower\x12\x0f.usi.SwitchInfo\x1a\x12.usi.PowerResponse\"\x00\x12\x39\n\x0cGetInterface\x12\x0f.usi.SwitchInfo\x1a\x16.usi.InterfaceResponse\"\x00\x12:\n\ndisconnect\x12\x0f.usi.SwitchInfo\x1a\x19.usi.SwitchActionResponse\"\x00\x12\x37\n\x07\x63onnect\x12\x0f.usi.SwitchInfo\x1a\x19.usi.SwitchActionResponse\"\x00\x42\x12\n\x04grpcB\x08USIProtoP\x01\x62\x06proto3'
)

_SWITCHMODEL = _descriptor.EnumDescriptor(
  name='SwitchModel',
  full_name='usi.SwitchModel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALLIED_TELESIS_X230', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CISCO_9300', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OVS_SWITCH', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=433,
  serialized_end=503,
)
_sym_db.RegisterEnumDescriptor(_SWITCHMODEL)

SwitchModel = enum_type_wrapper.EnumTypeWrapper(_SWITCHMODEL)
_LINKSTATUS = _descriptor.EnumDescriptor(
  name='LinkStatus',
  full_name='usi.LinkStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=505,
  serialized_end=535,
)
_sym_db.RegisterEnumDescriptor(_LINKSTATUS)

LinkStatus = enum_type_wrapper.EnumTypeWrapper(_LINKSTATUS)
_POESUPPORT = _descriptor.EnumDescriptor(
  name='POESupport',
  full_name='usi.POESupport',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENABLED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=537,
  serialized_end=576,
)
_sym_db.RegisterEnumDescriptor(_POESUPPORT)

POESupport = enum_type_wrapper.EnumTypeWrapper(_POESUPPORT)
_POESTATUS = _descriptor.EnumDescriptor(
  name='POEStatus',
  full_name='usi.POEStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAULT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=578,
  serialized_end=627,
)
_sym_db.RegisterEnumDescriptor(_POESTATUS)

POEStatus = enum_type_wrapper.EnumTypeWrapper(_POESTATUS)
ALLIED_TELESIS_X230 = 0
CISCO_9300 = 1
OVS_SWITCH = 2
UP = 0
DOWN = 1
ENABLED = 0
DISABLED = 1
ON = 0
OFF = 1
FAULT = 2
DENY = 3



_SWITCHACTIONRESPONSE = _descriptor.Descriptor(
  name='SwitchActionResponse',
  full_name='usi.SwitchActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='usi.SwitchActionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=57,
)


_POWERRESPONSE = _descriptor.Descriptor(
  name='PowerResponse',
  full_name='usi.PowerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_power_consumption', full_name='usi.PowerResponse.current_power_consumption', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_power_consumption', full_name='usi.PowerResponse.max_power_consumption', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poe_support', full_name='usi.PowerResponse.poe_support', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='poe_status', full_name='usi.PowerResponse.poe_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=215,
)


_INTERFACERESPONSE = _descriptor.Descriptor(
  name='InterfaceResponse',
  full_name='usi.InterfaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='link_status', full_name='usi.InterfaceResponse.link_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link_speed', full_name='usi.InterfaceResponse.link_speed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duplex', full_name='usi.InterfaceResponse.duplex', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=310,
)


_SWITCHINFO = _descriptor.Descriptor(
  name='SwitchInfo',
  full_name='usi.SwitchInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_addr', full_name='usi.SwitchInfo.ip_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_port', full_name='usi.SwitchInfo.device_port', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='usi.SwitchInfo.model', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='usi.SwitchInfo.username', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='usi.SwitchInfo.password', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=431,
)

_POWERRESPONSE.fields_by_name['poe_support'].enum_type = _POESUPPORT
_POWERRESPONSE.fields_by_name['poe_status'].enum_type = _POESTATUS
_INTERFACERESPONSE.fields_by_name['link_status'].enum_type = _LINKSTATUS
_SWITCHINFO.fields_by_name['model'].enum_type = _SWITCHMODEL
DESCRIPTOR.message_types_by_name['SwitchActionResponse'] = _SWITCHACTIONRESPONSE
DESCRIPTOR.message_types_by_name['PowerResponse'] = _POWERRESPONSE
DESCRIPTOR.message_types_by_name['InterfaceResponse'] = _INTERFACERESPONSE
DESCRIPTOR.message_types_by_name['SwitchInfo'] = _SWITCHINFO
DESCRIPTOR.enum_types_by_name['SwitchModel'] = _SWITCHMODEL
DESCRIPTOR.enum_types_by_name['LinkStatus'] = _LINKSTATUS
DESCRIPTOR.enum_types_by_name['POESupport'] = _POESUPPORT
DESCRIPTOR.enum_types_by_name['POEStatus'] = _POESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwitchActionResponse = _reflection.GeneratedProtocolMessageType('SwitchActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHACTIONRESPONSE,
  '__module__' : 'usi_pb2'
  # @@protoc_insertion_point(class_scope:usi.SwitchActionResponse)
  })
_sym_db.RegisterMessage(SwitchActionResponse)

PowerResponse = _reflection.GeneratedProtocolMessageType('PowerResponse', (_message.Message,), {
  'DESCRIPTOR' : _POWERRESPONSE,
  '__module__' : 'usi_pb2'
  # @@protoc_insertion_point(class_scope:usi.PowerResponse)
  })
_sym_db.RegisterMessage(PowerResponse)

InterfaceResponse = _reflection.GeneratedProtocolMessageType('InterfaceResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTERFACERESPONSE,
  '__module__' : 'usi_pb2'
  # @@protoc_insertion_point(class_scope:usi.InterfaceResponse)
  })
_sym_db.RegisterMessage(InterfaceResponse)

SwitchInfo = _reflection.GeneratedProtocolMessageType('SwitchInfo', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHINFO,
  '__module__' : 'usi_pb2'
  # @@protoc_insertion_point(class_scope:usi.SwitchInfo)
  })
_sym_db.RegisterMessage(SwitchInfo)


DESCRIPTOR._options = None

_USISERVICE = _descriptor.ServiceDescriptor(
  name='USIService',
  full_name='usi.USIService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=630,
  serialized_end=869,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPower',
    full_name='usi.USIService.GetPower',
    index=0,
    containing_service=None,
    input_type=_SWITCHINFO,
    output_type=_POWERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInterface',
    full_name='usi.USIService.GetInterface',
    index=1,
    containing_service=None,
    input_type=_SWITCHINFO,
    output_type=_INTERFACERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnect',
    full_name='usi.USIService.disconnect',
    index=2,
    containing_service=None,
    input_type=_SWITCHINFO,
    output_type=_SWITCHACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='usi.USIService.connect',
    index=3,
    containing_service=None,
    input_type=_SWITCHINFO,
    output_type=_SWITCHACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USISERVICE)

DESCRIPTOR.services_by_name['USIService'] = _USISERVICE

# @@protoc_insertion_point(module_scope)
