FROM daqf/aardvark:latest

RUN $AG update && $AG install python python-setuptools python-pip netcat

RUN pip install --upgrade pip
RUN pip install scapy

COPY subset/dhcp/dhcp_tests.py .
COPY subset/dhcp/test_dhcp .

CMD ["./test_dhcp"]
