## Image name: daqf/faucet

FROM faucet/python3:5.0.1

RUN apk add -q build-base

COPY faucet/ /faucet-src/

# We don't need no stinkin' unit-tests...
RUN sed -i 's/.*unit.*//' /faucet-src/docker/install-faucet.sh

RUN /faucet-src/docker/install-faucet.sh && rm -rf /faucet-src/.git

# Check for target executable since installer doesn't error out properly.
RUN which faucet

RUN apk add -q tcpdump iptables

CMD ["faucet"]
