# Image name: daqf/networking
#
# Image used for testing a mock OpenFlow switch.
#

FROM daqf/aardvark:latest

RUN $AG update && $AG install netcat python

COPY docker/include/bin/block_forever .

CMD ./block_forever
