# Image name: daqf/networking
#
# Image used for host networking services (DNS, DHCP, etc...)
#

FROM daqf/aardvark:latest

RUN $AG update && $AG install dnsmasq ethtool iptables netcat ntp python curl

COPY docker/include/network/scripts/* ./
RUN mkdir -p /etc
COPY docker/include/etc/ntp.conf /etc

# Weird workaround for problem running tcdump in a privlidged container.
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump

ENTRYPOINT ["./start_networking"]
