## Image name: daqf/faucet

FROM faucet/python3:5.0.1

RUN apk add -q build-base

COPY faucet/ /faucet-src/

RUN /faucet-src/docker/install-faucet.sh && rm -rf /faucet-src/.git

# Check for target executable since installer doesn't error out properly.
RUN which faucet

RUN apk add -q tcpdump iptables

ENV FAUCET_EVENT_SOCK_HEARTBEAT=5

CMD ["faucet"]
