name: DAQ perodic tests

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [base, many, aux, topo, modules, dhcp]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Installing dependencies
      run: |
        bin/setup_daq
    - name: Running ${{ matrix.test }} test
      env:
        DOCKER_STARTUP_TIMEOUT_MS: 60000
        GCP_BASE64_CRED: ${{ secrets.GCP_BASE64_CRED }}
      run: |
        DAQ_TEST=${{ matrix.test }} bin/test_daq
