# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DAQ test suite

on:
  push:
  pull_request:
  schedule:
    - cron: '0 16 * * *'

jobs:
  unit_tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        GIT_URL: ${{ secrets.GIT_URL }}
      run: |
        bin/setup_dev
    - name: Check style
      run: |
        bin/check_style
    - name: Unit test
      run: |
        testing/run_unit_tests.sh

  usi_tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B clean compile test assembly:single --file usi/pom.xml
