# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DAQ test suite

on:
  push:
  pull_request:
  schedule:
    - cron: '0 16 * * *'

jobs:
  test_fot:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        build: [a, b, c, d, e]
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: setup forch
        env:
          GIT_URL: ${{ secrets.GIT_URL }}
        run: |
          set -x
          bin/setup_remote forch
          git rev-list HEAD --max-count=1 > forch/etc/DAQ_VERSION
          cd forch
          bin/setup_base
          bin/setup_remote faucet
          bin/setup_remote daq
          bin/retry_cmd bin/build_docker controller
          bin/build_dts
      - name: run vxlan integration tests
        if: ${{ always() }}
        run: |
          cd forch
          bin/retry_cmd bin/run_fot_test vxlan
      - name: run dts integration tests
        run: |
          cd forch
          bin/retry_cmd bin/run_fot_test dts localhost
      - name: post-run logs
        if: ${{ always() }}
        run: |
          cd forch
          echo %%%%%%%%%%%%% Controller log
          docker logs forch-controller-1
          echo %%%%%%%%%%%%% DAQ log
          cat inst/forch-controller-1/daq/inst/cmdrun.log || cat inst/forch-dts/cmdrun.log
          echo %%%%%%%%%%%%% Forch log
          cat inst/forch-controller-1/forch.log
          echo %%%%%%%%%%%%% Faucet log
          cat inst/forch-controller-1/faucet.log
          echo %%%%%%%%%%%%% Endpoint log
          cat inst/endpoint.log || true
          echo %%%%%%%%%%%%% Log lengths
          find inst -name \*.log | fgrep -v nodes/ | xargs wc -l
