# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DAQ test suite

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [base, many, aux, topo, modules, dhcp]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Installing dependencies
      run: |
        bin/setup_daq
    - name: Running ${{ matrix.test }} test
      env:
        DOCKER_STARTUP_TIMEOUT_MS: 60000
        GCP_BASE64_CRED: ${{ secrets.GCP_BASE64_CRED }}
      run: |
        bin/test_daq ${{ matrix.test }}
    - name: Generated test report
      if: ${{ always() }}
      run: |
        echo '************* Use sed to filter out timestamp prefix *************'
        echo 'Download log archive, find the right job, and use:'
        echo "  sed -e 's/^[-:.0-9TZ]\+ //' 7_Generated\ test\ report.txt"
        cat inst/test_${{ matrix.test }}.out

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        bin/setup_dev
    - name: Check style
      run: |
        bin/check_style
    - name: Unit test
      run: |
        testing/run_unit_tests.sh

  usi_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B clean compile test assembly:single --file usi/pom.xml
