# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DAQ test suite

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build_docker:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        build: [faucet, faux, setup, base, subset]
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing dependencies
      env:
        GIT_URL: ${{ secrets.GIT_URL }}
      run: |
        bin/setup_daq
    - name: Build docker images for tests
      run: |
          bin/test_build ${{ matrix.build }} compress /tmp/build_artifacts/docker_images/
    - uses: actions/upload-artifact@v2
      with:
          name: build_artifacts_${{ matrix.build  }}
          path: /tmp/build_artifacts/

  integration_tests:
    needs: build_docker
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        test: [dhcp]
    steps:
    - uses: actions/download-artifact@v2
      with:
          name: build_artifacts_faucet
          path: /tmp/build_artifacts_faucet
    - uses: actions/download-artifact@v2
      with:
          name: build_artifacts_faux
          path: /tmp/build_artifacts_faux
    - uses: actions/download-artifact@v2
      with:
          name: build_artifacts_setup
          path: /tmp/build_artifacts_setup
    - uses: actions/download-artifact@v2
      with:
          name: build_artifacts_base
          path: /tmp/build_artifacts_base
    - uses: actions/download-artifact@v2
      with:
          name: build_artifacts_subset
          path: /tmp/build_artifacts_subset
      if: matrix.test == 'aux'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Installing dependencies
      env:
        GIT_URL: ${{ secrets.GIT_URL }}
      run: |
        bin/setup_daq
    - name: Loading docker images
      run: |
        bin/load_images faucet faux setup base
    - name: Loading subset docker images
      run: |
        bin/load_images subset
      if: matrix.test == 'aux'
    - name: Running ${{ matrix.test }} test
      env:
        DOCKER_STARTUP_TIMEOUT_MS: 60000
        GCP_BASE64_CRED: ${{ secrets.GCP_BASE64_CRED }}
        GCP_REFLECT_KEY_BASE64: ${{ secrets.GCP_REFLECT_KEY_BASE64 }}
      run: |
        bin/test_daq ${{ matrix.test }}
    - name: Generated test report
      if: ${{ always() }}
      run: |
        echo '************* Use sed to filter out timestamp prefix *************'
        echo 'Download log archive, find the right job, and use:'
        echo "  sed -e 's/^[-:.0-9TZ]\+ //' 7_Generated\ test\ report.txt"
        cat inst/test_${{ matrix.test }}.out

  unit_tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        GIT_URL: ${{ secrets.GIT_URL }}
      run: |
        bin/setup_dev
    - name: Check style
      run: |
        bin/check_style
    - name: Unit test
      run: |
        testing/run_unit_tests.sh

  usi_tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B clean compile test assembly:single --file usi/pom.xml
