FROM daqf/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git
RUN $AG update && $AG install curl
RUN $AG update && $AG install ncrack hydra nmap

COPY subset/security .
RUN cd security_passwords && ./gradlew shadowJar
CMD ["./test_password"]
