FROM daq/aardvark:latest

RUN $AG update && $AG install openjdk-8-jre
RUN $AG update && $AG install openjdk-8-jdk git
RUN $AG update && $AG install curl
RUN $AG update && $AG install ncrack

COPY subset/security .
COPY subset/helpers/reporting_utils .
RUN  curl https://svn.nmap.org/nmap/nmap-mac-prefixes | tee security_passwords/src/main/resources/macList.txt
RUN cd security_passwords && ./gradlew shadowJar
CMD ["./test_password"]
