FROM daqf/aardvark:latest

# Get dependencies
RUN $AG update && $AG install curl hydra nmap git

COPY subset/security/password .

# Create the brute force dictionary
CMD ["./create_brute_force_dictionary", $TARGET_MAC]

# Run the test
CMD ["./test_password"]
