#!/bin/bash -e
source reporting.sh
REPORT=/tmp/report.txt
LOCAL_REPORT=tmp/report.txt

RESULT_LINES=/tmp/result_lines.txt
MONO_LOG=/tmp/mono-log.txt
DEVICE_CONFIG=/config/device/
MANIFEST=./tls.module_manifest.json
MODULE_CONFIG=/config/device/module_config.json

if [ -n "$TARGET_IP" ]; then
    echo Collecting TLS cert from target address %% $TARGET_IP > $MONO_LOG

    export CA_FILE="None"
    if [ -f "$MODULE_CONFIG" ]; then
      echo "Module Config present"
      CA_FILE=`jq -r .modules.tls.ca_file $MODULE_CONFIG`
    elif [ -f "$DEVICE_CONFIG/CA_Faux.pem" ]; then
      echo "CA Faux found"
      #Module test won't have a module_config file but injects the CA file
      #directly where it should be
      CA_FILE="CA_Faux.pem"
    fi

    java -jar tlstest/build/libs/tlstest.jar $TARGET_IP $CA_FILE

    grep "RESULT" $LOCAL_REPORT | tee -a $RESULT_LINES
    grep -v "RESULT" $LOCAL_REPORT | tee -a $MONO_LOG

    write_out_monolog $REPORT \
                      $MANIFEST \
                      $MONO_LOG \
                      $RESULT_LINES

else
    echo "TARGET_IP not configured TLS test failed" > $MONO_LOG
    cat $MONO_LOG

    write_out_monolog $REPORT \
                      $MANIFEST \
                      $MONO_LOG \
                      $RESULT_LINES

fi

