#!/bin/bash -e

source reporting.sh
REPORT=./reports/report.txt
TEST_NAME=""
TEST_DESC="Verify all default password have been updated. Ensure new Google provided passwords are set"


if [ -n "$TARGET_IP" ]; then
	echo Using the host address from $TARGET_IP and mac address $TARGET_MAC

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP http 80 $TARGET_MAC nginx-site
write_out_result $REPORT \
                 					"security.passwords.http" \
							"$TEST_DESC" \
						        "Redacted Log" \
 						        "$(cat ./reports/http_report.txt)"

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP https 443 $TARGET_MAC nginx-site
write_out_result $REPORT \
							 "security.passwords.https" \
							 "$TEST_DESC" \
							 "Redacted Log" \
							 "$(cat ./reports/https_report.txt)"

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP telnet 23 $TARGET_MAC nginx-site
write_out_result $REPORT \
							 "security.passwords.telnet" \
							 "$TEST_DESC" \
							 "Redacted Log" \
							 "$(cat ./reports/telnet_report.txt)"

	java -jar security_passwords/build/libs/security_passwords-1.0-SNAPSHOT-all.jar $TARGET_IP ssh 22 $TARGET_MAC nginx-site
write_out_result $REPORT \
							 "security.passwords.ssh" \
							 "$TEST_DESC" \
							 "Redacted Log" \
							 "$(cat ./reports/ssh_report.txt)"

	cp -r ./reports/report.txt /tmp/report.txt
else
	echo Wrong parametres Password test failed | tee /tmp/report.txt
fi
